scullyio/scully

blog/page-1.md, blog/page-2.md, blog/page-3.md, projects/sampleBlog/src/app/app-routing.module.ts, projects/sampleBlog/src/app/app.component.css, projects/sampleBlog/src/app/app.component.html, projects/sampleBlog/src/app/blog/blog-list/blog-list.component.css, projects/sampleBlog/src/app/blog/blog-list/blog-list.component.html, projects/sampleBlog/src/app/blog/blog-list/blog-list.component.spec.ts, projects/sampleBlog/src/app/blog/blog-list/blog-list.component.ts, projects/sampleBlog/src/app/blog/blog-routing.module.ts, projects/sampleBlog/src/app/blog/blog.module.ts, projects/sampleBlog/src/app/demo/demo.component.css, projects/sampleBlog/src/app/static/static-routing.module.ts, projects/sampleBlog/src/app/static/static.component.css, projects/sampleBlog/src/app/static/static.component.html, projects/sampleBlog/src/app/static/static.component.ts, projects/sampleBlog/src/app/user/user.component.css, projects/scullyio/ng-lib/src/lib/scully-content/scully-content.component.ts, scully.config.js, scully/renderPlugins/contentRenderPlugin.ts, scully/routerPlugins/addOptionalRoutesPlugin.ts, scully/utils/defaultAction.ts, scully/utils/log.ts
- Updated the error messages in Scully-content to me more explanatory
- updated the error for the missing <suclly-content> during generation
- updated demo plugin to `extraRoutesPlugin` to make it actually useful
- reworked the home page to use the route for full/top-level routes list
- this also uses the extraRoutesPlugin
- added a top-level blog route that lists all the blogs
=> More and improved samples and error messages

scully/utils/staticServer.ts
There was an incorrect spelling in a log during Scully serve.
=> Fix log spelling

scully/package.json, scully/utils/validateConfig.ts
- rename config file in error message to 'scully.config.js'
Fixes #28
=> fix(cli): fs_extra_1.pathExists is not a function

projects/scullyio/ng-lib/src/lib/route-service/scully-routes.service.ts
The `slugs` property of `ScullyRoute` is currently typed as an array of **empty** strings.
This probably doesn't cause any errors right now, but unless this is intentional, I suggest we use a more appropriate type.
=> fix: type slugs as possibly non-empty

extraPlugin/extra-plugin.js, scully.config.js, scully/pluginManagement/pluginRepository.ts
This pr makes configvalidatios optional.
closes #64
=> feat(registerplugin): make configValidators optional

projects/scullyio/ng-lib/package.json, projects/scullyio/ng-lib/src/lib/components.module.ts
Instead of loading in the module in ng-lib get the httpclient dep
closes #52
=> fix(ng-lib): correct httpclient import

extraPlugin/extra-plugin.js, scully/fileHanderPlugins/asciidoc.ts, scully/package-lock.json
This pr hides the asciidoc warings and errors.
closes #61
=> fix(asciidoc logging): hide the asciidocs logging

projects/scullyio/ng-lib/src/lib/components.module.ts
Correctly expose a `ModuleWithProviders`.
Fixes #52 and corrects #69
=> fix(ng-lib): correct ModuleWithProviders

package-lock.json, package.json, projects/sampleBlog/e2e/protractor.conf.js, projects/scullyio/ng-lib/src/public-api.ts, scully/renderPlugins/contentRenderPlugin.ts, scully/renderPlugins/routeContentRenderer.ts, scully/utils/compileConfig.ts, scully/utils/config.ts, scully/utils/defaultAction.ts, scully/utils/findAngularJsonPath.ts, scully/utils/fsAngular.ts, scully/utils/fsFolder.ts, scully/utils/httpGetJson.ts, scully/utils/isPortTaken.ts, scully/utils/restart.ts, scully/utils/startup.ts, scully/utils/validateConfig.ts
- remove some unused imports
- shorten some import paths
- fix variables with the same name in the same scope
=> fix(scully): lint issues and typos

CONTRIBUTING.md
add the Signing the CLA section into CONTRIBUTING.md
Solve #84
Issue Number: #84 
Link to CLA's, Individuals and Corporations:
**cla-individual**: https://gist.github.com/Villanuevand/88bc07f18ec051e8ad32b789a0a806d1
**cla-corporations**: https://gist.github.com/Villanuevand/4178efad870e8397565c6944fc3d292d
=> docs(scully): add signing the cla section

projects/scullyio/ng-lib/src/lib/idleMonitor/idle-monitor.service.spec.ts, projects/scullyio/ng-lib/src/lib/route-service/scully-routes.service.spec.ts, projects/scullyio/ng-lib/src/lib/scully-content/scully-content.component.spec.ts
Test suites fail.
Test suites succeed.
Use `npm run test -- @scullyio/ng-lib` to verify.
=> test(ng-lib): working test suites

scully/scully.ts, scully/utils/config.ts
Currently scully always emits a `0` as exit code, even when it fails. Emitting a non-zero exit code is essential if you want to use scully in an automated process, as it will halt the process if something fails - currently it just continues.
Emit exit code 5 ([Fatal exception](https://nodejs.org/api/process.html#process_exit_codes)) when something fails.
=> fix(scully): make sure scully emits non-zero exit code on errors

extraPlugin/extra-plugin.js, package-lock.json, package.json, projects/sampleBlog/src/app/app-routing.module.ts, scully.config.js, scully/package-lock.json, scully/package.json, scully/renderPlugins/launchedBrowser.ts, scully/utils/compileConfig.ts, scully/utils/validateConfig.ts
- [ x] The commit message follows our guidelines: https://github.com/scullyio/scully/blob/master/CONTRIBUTING.md#commit
- [x ] Other... Please describe:
Improves ease of plugins
get rid of the protective context to make registering plugins easier.
Also, add an cmd-line option for alternate config files (--cf)
also, add on cmd-line option to show the browser (--sb)
- [ x] No
=> Config load with require

schematics/scully/package.json, scully/package-lock.json, scully/package.json
This should be a start to tackle this issue:
Issue Number: #88 
Dependencies needed only during development are moved to the `devDependencies` object. 
I checked these pages and found that almost none of the devDependencies are marked as such:
https://www.npmjs.com/package/@scullyio/scully?activeTab=dependencies
https://www.npmjs.com/package/@scullyio/init?activeTab=dependencies
There might be more deps that can be moved, but this should be a good start.
=> fix: make sure devDependencies are marked as such

docs/getting-started.md
consider this doc change as it may lead to a bad initial experience
=> chore(docs): improve getting started

scully/renderPlugins/launchedBrowser.ts
Currently when running scully in a Docker container it fails with an error message similar to this:
```
Error: Failed to launch chrome! spawn /workspace/node_modules/puppeteer/.local-chromium/linux-706915/chrome-linux/chrome ENOENT
```
This PR adds the option to instruct Scully to use an existing chromium as executable, allowing it to run inside a Docker container.
It introduces support for the `SCULLY_PUPPETEER_EXECUTABLE_PATH` env var, if this is found it uses it's value as the `executablePath` for Puppeteer.
This allows for running Scully with a prepared Docker image, like [beeman/scully-docker](https://hub.docker.com/r/beeman/scully-docker).
After this patch, scully uses the …
=> feat(sully): prepare scully for running inside Docker container

scully/renderPlugins/puppeteerRenderPlugin.ts
closes #74
`<!doctype html>` is removed from generated `index.html`.
Issue Number: #74
`<!doctype html>` remains.
=> fix(scully): render doctype

scully/index.ts, scully/utils/replaceFirstRouteParamWithVal.ts
I have added a util function for plugin authors who need to replace the first parameterized value in a route with a provided value. It is simple, but could go wrong. 
this will make life easier for plugin authors who will be doing this often. 
=> feat(scully): Add replaceFirstRouteParamWithVal util 

scully/utils/defaultAction.ts, scully/utils/interfacesandenums.ts
With the additional of extraRoutes to the scully.config, users can now provide additional routes
that they want Scully to discover. These routes can plug into the router plugins as well, and can
produce multitudes of browsable routes each.
I need this feature to integrate with our first big enterprise client. 
In your scully config, you can now provide an extraRoutes that looks like an Angular route (meaning it contains parameters). These can be routes that exist in AngularJS, or in React, or in whatever Framework's router. What's really important is that this unlocks our ability to support Angular Hybrid scenarios where some routes are controlled by Angular and others controlled by AngularJS. The Guessjs parser will find the Angular routes. But won't find the AngularJS routes. This …
=> feat(config): add extraRoutes to scully.config

scully/routerPlugins/addOptionalRoutesPlugin.ts
When plugins generate routes for scully, we need to validate that the handledRoutes.route start with
/. In this change we show a warning.
Add validation to Handled Routes.
=> improvement(scully): add routes validation

projects/scullyio/ng-lib/src/lib/scully-content/scully-content.component.ts
closes #121
fixes a bug that ahppened when you navigated from a blog page to a level above. It tried to render the scully content for the new page, where it should not do that,
throws error:
Issue Number: 121
doesn't throw the error anymore
=> fix(scully-content.component): don't try to re-render content when navigating one level "up"

schematics/scully/src/add-post/schema.json, schematics/scully/src/create-markdown/schema.json, schematics/scully/src/ng-add/schema.json
While running the schematics (`ng-add` or `generate`) we have to remember the options. 
If we don't add options, the schematic will do nothing.
The user will be prompted if she doesn't provide the options:
Formatting is changed due to prettier.
=> feat(schematics): add prompts

projects/scullyio/ng-lib/src/lib/transfer-state/transfer-state.service.ts
Fixing an ngc error around using Document as a DI token.
=> feat(transferstateservice): Fix ngc error

projects/sampleBlog/src/app/app-routing.module.ts, projects/sampleBlog/src/app/user/user.component.html, projects/sampleBlog/src/app/user/user.component.ts, scully.config.js, scully/renderPlugins/index.ts, scully/renderPlugins/puppeteerRenderPlugin.ts, scully/routerPlugins/index.ts, scully/routerPlugins/jsonRoutePlugin.ts, scully/utils/interfacesandenums.ts
I needed to show people how to use transferstate. I also added in this commit a `resultsHandler`
param to the json plugin. This makes it so you can have a bit more power when mapping responses to
data.
=> docs(transferstate): add TransferState example to sampleBlog

projects/scullyio/ng-lib/src/lib/route-service/scully-routes.service.ts
Put in the correct type for the return of the getCurrent function. In some cases TS inferrrence is
off otherwise
closes #171
typing of the getCurrent method is off
Issue Number: #171 
It returns the correct type.
=> fix(scully-routes.service): fix missing return type

docs/polyfills.md, docs/scully.md
The `Event()` constuctor is used in the project. To make this work in Internet Explorer, a polyfill is required.
The new document describes the polyfilling process.
Scully is currently not working in Internet Explorer.
The new doc describes the necessary polyfilling process.
Reference to usage of `new Event()`: https://github.com/scullyio/scully/blob/27b79ddb454539c43ca1fa7048aa97c40f8ddee8/projects/scullyio/ng-lib/src/lib/idleMonitor/idle-monitor.service.ts#L25-L27
=> docs: add polyfill.md

scully.config.js, scully/renderPlugins/puppeteerRenderPlugin.ts, scully/scully.ts, scully/startBackgroundServer.ts, scully/tsconfig.scully.json, scully/utils/fsAngular.ts, scully/utils/fsFolder.ts, scully/utils/httpGetJson.ts, scully/utils/isPortTaken.ts, scully/utils/staticServer.ts, scully/utils/waitForServerToBeAvailable.ts, scully/watchMode.ts, tsconfig.json
Fix problem with Could not connect to server
Issue Number: #40
=> fix(scully): fix Could not connect to server

schematics/scully/src/add-blog/index_spec.ts, schematics/scully/src/ng-add/index.ts, schematics/scully/src/ng-add/index_spec.ts, schematics/scully/src/scully/index_spec.ts
`ng-add` didn't work (0.0.10)
Verification that other schematics will be called when running `ng-add`
=> refactoring/tests `ng add`

docs/scully-configuration.md, scully/renderPlugins/launchedBrowser.ts, scully/utils/interfacesandenums.ts
closes #181
add an option to the config to set puppeteers launch options. might be needed in restricted environments
None
Issue Number: #181 
have an option to address #181
=> feat(Scully config): adds an option to set the puppeteer launch options

scully.config.js, scully/renderPlugins/puppeteerRenderPlugin.ts, scully/utils/config.ts, scully/utils/interfacesandenums.ts
=> feat(puppeteerrenderplugin): add support for hostURL

schematics/scully/src/ng-add/index.ts
Schematics import wrong version into app.component when you are in angular v8 project
=> fix(ng-add): fix v8 import

scully/pluginManagement/pluginRepository.ts
To make writing plugins easier, the validator is now a parameter to the registerPlugin function.
Also the resiterPlugin functin now checks its types.
=> feat(pluginrpository.ts): refactor registerplugin to take validator

schematics/scully/src/add-plugin/index.ts, schematics/scully/src/add-plugin/schema.json, schematics/scully/src/add-plugin/schema.ts, schematics/scully/src/collection.json, schematics/scully/src/files/plugin/__name@dasherize__.plugin.js.template, schematics/scully/src/utils/utils.ts
Add new schematics for create a custom plugin
=> feat(add-plugin): add schematics for create a new custom plugin

schematics/scully/src/create-markdown/index.ts, schematics/scully/src/create-markdown/index_spec.ts, schematics/scully/src/scully/index_spec.ts, schematics/scully/src/utils/utils.ts
=> feat: use only ascii chars within route option

docs/plugins.md
> Add more information about `registerPlugin` method. 
Issue Number: #127
=> docs(scully): add registerPlugin explanation

scully/renderPlugins/content-render-utils/insertContent.ts, scully/renderPlugins/contentRenderPlugin.ts
=> refactor(content): fix typo into log

package-lock.json, package.json, projects/sampleBlog/src/app/app-routing.module.ts, scully.config.js, scully/package.json, scully/routerPlugins/traverseAppRoutesPlugin.ts, scully/utils/defaultAction.ts, scully/utils/waitForServerToBeAvailable.ts
This pr adds better handling when we fail to traverse routes in the angular app, and explains the
most common reasons.
closes #40
Scully throws a non-descript error (`could not connect to server`) when it can not properly parse the routes n the application
Issue Number: #40
It describes what happened and gives you a path to a solution to the issue.
Also, it warns when there is no ` ` (empty) home route.
=> fix(could not connect to server): explain the reasons

projects/scullyio/ng-lib/package.json, projects/scullyio/ng-lib/src/lib/route-service/scully-routes.service.ts, scully/package.json, scully/utils/defaultAction.ts
When used in a specific way, the route-service coulsderror out. This fixes that issue
When the route file isn't created yet and is used in a specific way, it can error, and break prerendering of the page
doesn't error anymore, and makes sure the page renders correctly
It also removes a stray debug console.log
=> fix(scullyroutesservice): dont error when nor routefile is found

scully/pluginManagement/pluginRepository.ts, scully/pluginManagement/systemPlugins.ts, scully/routerPlugins/ignoredRoutePlugin.ts
When given the wrong type for a plugin, throw a proper explaination.
closes #219
The current error message isn't explanatory enough
throw an error like this:
```
--------------
Type "tourer" is not a known plugin type for registering plugin "myPluginName".
The first parameter of registerPlugin needs to be one of: 'fileHandler', 'router', 'render'
--------------
```
=> fix(registerplugin): better error on type

scully.config.js, scully/routerPlugins/traverseAppRoutesPlugin.ts, scully/utils/interfacesandenums.ts
When using the extraroutes option to add an empty route to render `/` scully errors out
closes #223
Scully breaks down when adding an empty route (`""`)
Issue Number: 223
Works as expected, and make sure the top `index.html` gets generated
=> fix(extrroutes): fix bug wehre extraroutes fails

projects/scullyio/ng-lib/package.json, projects/scullyio/ng-lib/src/lib/scully-content/scully-content.component.ts
This will add an `id="___scully-parsing-error___"` to Scully rendering errors so that it will be
easier to detect those during CI/CD steps.
closes #228
No detectable id is there when there is a Scully rendering issue
Issue Number: #228
`id="___scully-parsing-error___"` is added
@Villanuevand You should mention this in the documentation.
=> feat(scullycontent): add a detectable Id to scully rendering errors

scully/renderPlugins/puppeteerRenderPlugin.ts
closes #239
When a page renders after timeout body-tag and scully-generated settings are not injected
Both are updated as expected
=> fix(pupperteerrenderplugn.ts): inject scully content on  timeout

docs/scully-cmd-line.md
Docs:  Add `--showGuessError` flag to docs. 
=> docs(scully): add showGuessError flag to docs

docs/getting-started.md, docs/getting-started_es.md
Add getting started page spanish translation
An almost literal translation of the content present on the current getting started page is performed.
It was decided to make a literal translation to maintain the author's intentionality at the time of writing the guide.
=> docs(scully): add getting started page spanish translation

scully/routerPlugins/traverseAppRoutesPlugin.ts
if there is no `/` route in the router, the index.html is the original version, and not rendered by Scully
The `/` route will always be rendered unless explicitly ignored by route configuration.
=> feat(traverseapparoutes): make sure there is allwyas an root Route `/`

blog/page-1.md, scully.sampleBlog.config.js, scully/renderPlugins/launchedBrowser.ts, scully/renderPlugins/puppeteerRenderPlugin.ts, scully/utils/config.ts
closes 194
Can't config puppeteer because it is launched before config is ready
Issue Number: 194
Make sure puppeteer is only launched after config is ready.
=> fix(launchedbrowser): wait for config to be available before launch puppeteer

projects/sampleBlog/src/app/app.module.ts, projects/scullyio/ng-lib/src/lib/config/scully-config.ts, projects/scullyio/ng-lib/src/lib/idleMonitor/idle-monitor.service.ts, projects/scullyio/ng-lib/src/lib/scully-lib.module.ts, projects/scullyio/ng-lib/src/lib/transfer-state/transfer-state.service.ts
The transferState service now only gets activated when the config using forRoot says so.
`transferStateService` is always monitoring the route, and trying to load data, even when `s/getState` is not used at all.
`transferStateService` is only monitoring if the user tells it so by using the config in forRoot
like this:
```typescript
@NgModule({
declarations: [AppComponent],
imports: [
BrowserModule,
HttpClientModule,
AppRoutingModule,
ScullyLibModule.forRoot({useTranferState: true}),
],
bootstrap: [AppComponent],
})
export class AppModule {}
```
=> feat(scully runtime config): user forRoot to pass config to Scully

scully/utils/defaultAction.ts
=> fix(scully): replace falsy check with explicit string check to allow root route

scully/routerPlugins/traverseAppRoutesPlugin.ts, scully/scully.ts, scully/utils/cli-options.ts, scully/utils/startup.ts, scully/utils/staticServer.ts
=> fix(traverseapp): looks in the different places for tsconfig.app.json

projects/scullyio/ng-lib/src/lib/transfer-state/transfer-state.service.ts, projects/scullyio/ng-lib/src/lib/utils/merge-paths.spec.ts, projects/scullyio/ng-lib/src/lib/utils/merge-paths.ts
Issue Number: #298 #299 #300 
#298 - correctly merge path to `index.html`
#299 - load `index.html` rather for `urlAfterRedirects` than for `url`.
#300 - use regex to correctly check initial route
=> Fixes for #298 #299 #300 in TransferStateService

scully/scully.ts, scully/utils/httpGetJson.ts, scully/utils/staticServer.ts
When using the SSL option, the killserver nor the --open will not work
both are working now
=> fix(scully.ts): supprt SSL on kill and launch

projects/scullyio/ng-lib/src/lib/route-service/scully-routes.service.ts, schematics/scully/src/add-post/index.ts, schematics/scully/src/add-post/index_spec.ts, schematics/scully/src/files/blog-add/blog-X.md
ScullyRoutesService observables looking for property `published` instead of `publish`;
Issue Number:  https://github.com/scullyio/scully/issues/316
=> Fix ScullyRoutesService

scully/scully.ts, scully/startBackgroundServer.ts, scully/utils/compileConfig.ts, scully/utils/config.ts, scully/utils/read-anguar-json.ts, scully/utils/staticServer.ts, scully/utils/waitForServerToBeAvailable.ts
This PR will allow for comments to be in the angular.json
ISSUES CLOSED: #307
Scully errors out when there are comments in the angular.json
It allows those comments while still able to parse the json
=> Allow comments in Angular.json

docs/blog.md, docs/getting-started.md, docs/plugins.md, docs/pre-requisites.md, docs/scully-cmd-line.md, docs/scully-configuration.md, docs/scully-lib-core.md, docs/utils.md
Several typos into the documentation.
Typos fixed.
=> docs: fix typos

projects/scullyio/ng-lib/src/lib/route-service/scully-routes.service.ts
change cleanDups to private as it's an implementation detail
`cleanDups` is publicly accessible but meant to be an implementation detail as stated by @SanderElias on Gitter : 
> the cleandups is private, it is an implementation detail. (as content-routes can have multiple instances this makes sure they are not leaking into the app, wreaking havoc on lists)
`cleanDups` is no longer accessible
=> refactor(ng-lib): change cleanDups to private

cypress/fixtures/example.json, scully/routerPlugins/contentFolderPlugin.ts
this adds a way to differentiate between different contentfolders
ISSUES CLOSED: #320
=> feat(scully): name option for contentfolderplugin

docs/getting-started.md, docs/getting-started_es.md, docs/plugins.md, schematics/scully/src/ng-add/index_spec.ts
remove HttpClientModule reference
remove HttpClientModule test
move plugin registration out of the list
`HttpClientModule` is not added anymore using `ng add @scullyio/init`.
There is still a test to check if `HttpClientModule` has been added to `AppModule`.
The link to the section about `how to register plugin` is misleading as being part of a list previously stated as a list of three plugins (router, render, file handler).
The `HttpClientModule` reference has been removed from the output message sample.
The corresponding test is removed.
The link to `how to register plugin` has been moved out of the list.
=> docs: update docs

scully/watchMode.ts
ScullyServer keeps running even though I quit it with Cmd + C or "q"
Issue Number: #339
Fix this error waiting for kill servers
=> fix(scully): watchMode: fix problem with ghost service in mac

docs/release-for-v8.md
=> Release V8 library

scully/utils/fsFolder.ts
In watch mode the folder location should point to the variable "slug" not the explicit folder "slug".
For example with a config settings: 
```js
exports.config = {
projectRoot: "./src",
projectName: "my-scully-blog",
outDir: "./dist/static",
routes: {
"/blog/:postId": {
type: "contentFolder",
postId: {
folder: "./blog"
}
}
}
};
``` 
and after `npm run scully` you will receive the following error:
```
error into read the config TypeError: Cannot read property 'folder' of undefined
at Object.checkStaticFolder (/Users/jiverson/dev/my-scully-blog/node_modules/@scullyio/scully/utils/fsFolder.js:24:64)
at Object.watchMode (/Users/jiverson/dev/my-scully-blog/node_modules/@scullyio/scully/watch …
```
=> fix: slug folder

docs/getting-started.md
ISSUES CLOSED: 358
Issue Number: #358
=> fix(docsWeb): getting-started: add router data

scully/index.ts, scully/utils/services/routeStorage.ts
with thsi PR you can get the full list of routes when you need it. It is only available _after_ the
routeDetection phase is done.
Issue Number: closes #374
=> feat(scully): make getHandledRoutes promise available

scully/package.json, scully/utils/fsAngular.ts
No 404 file
Issue Number: closes #361 
Copies the `index.html` (the original angular app) to `404.html`  when that doesn't exist. You can now redirect your server to this file if there is no route file available.
=> feat(scully): add 404.html to redirect to.

docs/scully-provided-plugins.md, projects/scullyio/ng-lib/src/lib/transfer-state/transfer-state.service.ts, scully/utils/config.ts, scully/utils/handlers/renderParallel.ts, scully/utils/interfacesandenums.ts
Currently, the number of concurrent rendering threads equals node `cpus().length` (all threads on all cores)
Have a setting in scullyconfig that allows changing this to whatever value fits the app.
Also, add a utility function to the transfer state that makes it easier to incorporate using the Scully state
=> feat(scully): add support to set the number of cores during rendering,

blog/page-2.md, cypress/integration/sampleBlog.spec.js, projects/scullyio/ng-lib/package.json, scully/package.json, scully/pluginManagement/systemPlugins.ts, scully/renderPlugins/contentRenderPlugin.ts, scully/renderPlugins/customMarkdownOptions.ts
allow additional attributes to be added to target  anchors. It uses the same syntax as jekyll and kramdownL
```markdown
[someLink](http://somewhere.com){:target="_blank" class="lnk ext"}
```
=> feat(scully): support for markdown options like `{:target="_blank"}`

scully/pluginManagement/pluginRepository.ts, scully/routerPlugins/jsonRoutePlugin.ts
validator attached on the wrong insertion point
the validators are properly attached
- [] Yes
=> fix(scully): attach validator correctly

schematics/scully/src/ng-add/index.ts, schematics/scully/src/ng-add/index_spec.ts
When using `ng add @scullyio/init` into a v8 project, the schematic checks the version to add the right dependency into the package.json file but it doesn't check it to add the right import into the AppModule file.
Resulting having :
```
// package.json
'@scullyio/ng-lib-v8'
// AppModule.ts
import { ScullyLibModule } from '@scullyio/ng-lib'
```
Issue Number: #419 
The schematic checks the angular version of the project for the import added into the AppModule file.
The PR removes a legacy test based on #242 action
=> fix(schematic): v8 support in AppModule

docs/scully-provided-plugins.md
typos
Sorry for multiple PRs, i just wanted to take a look at previous merged PRs this time to check typos.
=> fix(documentation): typo

projects/scullyDocs/src/app/app.component.html
Links to "Docs" "Get started" and "Contributing" on the footer of scully.io site are broken.
Links to "Docs" "Get started" and "Contributing" on the footer of scully.io site are working.
=> docs(docsWeb): fix broken footer links

docs/getting-started.md
The [Getting started with Scully](https://github.com/scullyio/scully/blob/master/docs/getting-started.md) doc page warns about the required router and the option to choose to add a default routing module (with the `ng new` schematic).
With the enhancement of the docs with #383, the app generation has been moved into the [Prerequisites](https://github.com/scullyio/scully/blob/master/docs/pre-requisites.md) page and this warning is already covered with an additionnal step to generate a routing module.
I took advantage of this PR to fix the number of topics being announced in the beginning of the page, as it includes only *Installation* and *Building* now.
The warning information is …
=> refactor(documentation): remove duplicate mention

.vscode/settings.json, scully/renderPlugins/content-render-utils/insertContent.ts, scully/renderPlugins/content-render-utils/readFileAndCheckPrePublishSlug.ts, scully/renderPlugins/contentRenderPlugin.ts
An error is thrown when `scully-content` is missing
An error is thrown when `scully-content` is missing, that more explained what happened, and teaches how to look for it in the app.
=> feat(scully): better handling of missing `<scully-content>`

docs/getting-started.md, docs/getting-started_es.md
Issue Number: #434 
remove `--nw` flag from docs
=> docs: remove old `--nw` flag

docs/utils.md
Add link to https://github.com/cmgriffing/scully-gh-pages-action
=> docs: add link to Scully Publish Github action

scully/utils/cli-options.ts, scully/utils/serverstuff/waitForServerToBeAvailable.ts
Now the timeout is fixed on approximately 10 seconds
Issue Number: should help #461 
you can set the timeout in milliseconds from the cmd line using the `--serverTimeout` flag
=> feat(scully): new flag to set timeout for serer during CI

scully.sampleBlog.config.js, scully/renderPlugins/puppeteerRenderPlugin.ts, scully/utils/config.ts, scully/utils/interfacesandenums.ts
None
optionally save a thumbnail for every route. Note that this doesn't work for content(blog) routes
=> feat(scully): add optional thumbnail to every route

generics/add/package-lock.json, generics/add/package.json, generics/add/src/index.ts, generics/add/src/install/index.ts, generics/add/src/npm/index.ts, generics/add/src/utils/utils.ts
=> style(lib): full support for `npx @scullyio/create` or `npm init @scullyio/scully`

ng-projects/scullyDocs/src/app/app.component.html
In the Header, the current docs site shows undefined in the path of the href. This breaks opening main menu links in a new tab.
The routerLink input is fixed to be link as expected by the app-button component.
=> fix(docsWeb): change routerLink to link on app-button in header

scully/renderPlugins/puppeteerRenderPlugin.ts
=> fix(scully): puppeteerRender: add validation for html with undefined

docs/scully-cmd-line.md, plugins/demos/errorPlugin.js, scully.sampleBlog.config.js, scully/pluginManagement/pluginWrap.ts, scully/renderPlugins/executePlugins.ts, scully/utils/cli-options.ts
…he flag for dont use this funct
Issue Number: #492 #493
=> feat(scully): add exit by default when have a plugin error and cli option

generics/lib/src/routeMonitor.ts, scully/package-lock.json, scully/package.json
We reply on Angular to detect route changes
This is the first step to monitor route changes that is framework agnostic, and doesn't use any angular provided things.
=> feat(lib): start of generic lib. Routemonitor

docs/blog.md, schematics/scully/package-lock.json, schematics/scully/package.json
=> refactor(docsWeb): blog: change some text

docs/getting-started.md, scully/renderPlugins/puppeteerRenderPlugin.ts
=> feat(scully): idle detection for non angular apps (experimental)

ng-projects/scullyio/ng-lib/src/lib/scully-content/scully-content.component.ts, ng-projects/scullyio/ng-lib/src/lib/utils/basePathOnly.ts, scully/routerPlugins/addOptionalRoutesPlugin.ts, tests/cypress/integration/sampleBlog.spec.js
When there is a search param `?` or a hash `#` in the URL, Scully rendered pages might fail
Scully generated pages now ignore those parts fo the URL, as there is no way those can be stored n a file system
=> fix(scully): handle `#` and `?` in urls properly

docs/blog.md, docs/getting-started.md, ng-projects/scullyDocs/src/app/app.component.html
- [X ] The commit message follows our guidelines: https://github.com/scullyio/scully/blob/master/CONTRIBUTING.md#commit
- [X ] Tests for the changes have been added (for bug fixes / features)
- [X ] Docs have been added / updated (for bug fixes / features)
I've fixed some small typos in the docs.
=> fix: fixed small typos

docs/pre-requisites.md, docs/pre-requisites_es.md
The schematic listed into the documentation `ng generate module app-routing --flat --module=app` adds a module without **RouterModule**
- move up the warning about RouterModule pre-requisite
- remove the schematic command adding a routing module
- add --routing to the existing creation commands
Close #534
=> docs(pre-requisites): change the RouterModule addition

docs/getting-started.md
=> docs(scully): fix typo in getting-started.md

libs/scully/src/scully.ts
- fixes a typo in the CLI output
```sh
> scully serve
starting
going to load
config loaed
before build
starting static server
```
```sh
> scully serve
starting
going to load
config loaded
before build
starting static server
```
=> fix(scully): typo loaed -> loaded

docs/scully-configuration.md, libs/scully/src/lib/utils/interfacesandenums.ts
No, but I think tests for types are not needed in this time.
Linter says "`defaultPostRenderers` is missing" which is an optional array.
https://github.com/scullyio/scully/blob/master/libs/scully/src/lib/utils/config.ts#L74
There should be no errors after the config file is generated.
The document for the interface is synchronized to the latest `ScullyConfig`.
=> fix(scully): fix defaultPostRenderers type

docs/blog.md, libs/scully-schematics/src/add-post/index.ts, libs/scully-schematics/src/add-post/index_spec.ts, libs/scully-schematics/src/add-post/schema.json, libs/scully-schematics/src/add-post/schema.ts
=> feat(schematics): allow specify a file extension when creating a post

libs/ng-lib/src/lib/route-service/scully-routes.service.ts
Condition
```
curLocation === r.route.trim()
```
does not work because `curLocation` is not decoded, so there are some extra symbols there.
=> fix(ng-lib): getCurrent method needs decodeURI

docs/getting-started.md
Issue Number: #501 
The current Getting Started docs are a bit vague on where Scully gets the data for `ScullyRouteService.available$` and how to add additional values to that data.
`getting-started.md` now references the `ScullyRoute` interface, explains how its shape corresponds to `.md` blog post metadata, and how to include these additional arbitrary values in a template.
=> docs: ✏️ add more descriptive examples to getting-started.md

docs/scully-configuration.md, libs/scully/src/lib/renderPlugins/puppeteerRenderPlugin.ts, libs/scully/src/lib/utils/interfacesandenums.ts
All images / fonts / stylesheets are currently also loaded in Puppeteer when requesting a page. In most cases they are not relevant for prerendering the HTML.
Any `ResourceType` that is listed here will be ignored by the Puppeteer instance rendering the requested page. For example if you add `image` and `fonts` all requests to images and fonts loaded on your pages will be blocked.
=> Feature to ignore specific ResourceTypes in Puppeteer

apps/sample-blog/src/app/about/about.component.html, libs/scully/src/lib/renderPlugins/seoHrefCompletionPlugin.ts, tests/jest/src/__tests__/seoOptimize.spec.ts
none.
All link that have `target="_blank"` get the attribute `rel="noreferrer noopener"` added to enhance security and SEO score
=> Add `rel="noreferrer noopener"` to anchors with `target="_blank"`

docs/getting-started.md
=> docs(getting-started): lack of `ng` in one command

libs/scully-plugin-flash-prevention/README.md, libs/scully-plugin-flash-prevention/package.json, libs/scully-plugin-flash-prevention/src/lib/flash-prevention.plugin.ts
When the flashPreventionPlugin is done, it sets the display type to inherit. 
the displayType is now an option, if you need something else as `inherit` you can now set this as an optional parameter.
=> feat(monorepo): add option to flashPrevention so set other display type

docs/scully-lib-core.md
There is no information present about how to disable scully ready mechanism and add custom one
Added information about the manualIdle flag and how to trigger the app ready event manually.
=> docs(lib-core): add more information about enabling manualIdle

libs/scully/src/lib/routerPlugins/addOptionalRoutesPlugin.ts, libs/scully/src/lib/routerPlugins/traverseAppRoutesPlugin.ts, libs/scully/src/lib/systemPlugins/storeRoutes.ts, libs/scully/src/lib/utils/compileConfig.ts
=> refactor(scully): move the cached routeData to its proper place

CONTRIBUTING.md
Contributing guidelines don't have a link to Scully gitter channel: `...you can reach out via our gitter channel (Coming soon)`
Added a link to Scully gitter channel
=> docs: replace coming soon note with gitter link

libs/plugins/scully-plugin-flash-prevention/src/lib/flash-prevention.plugin.ts
Add scroll event
support scroll position when the transfer state run
=> feat(lib): flashPrevention: add scroll prevention

libs/scully/package.json, libs/scully/src/lib/startBackgroundServer.ts, libs/scully/src/lib/utils/log.ts, libs/scully/src/lib/utils/serverstuff/handleUnknownRoute.ts, libs/scully/src/lib/utils/serverstuff/staticServer.ts
=> fix(scully): fix config handling when option `--404=''`

libs/ng-lib/package.json, libs/plugins/base-href-rewrite/package.json, libs/plugins/extra/package.json, libs/plugins/from-data/package.json, libs/plugins/scully-plugin-flash-prevention/package.json, libs/scully-schematics/package.json, libs/scully/package.json, libs/scully/src/index.ts, libs/scully/src/lib/pluginManagement/pluginConfig.ts, libs/scully/src/lib/pluginManagement/pluginRepository.ts, libs/scully/src/lib/pluginManagement/pluginWrap.ts, libs/scully/src/lib/renderPlugins/launchedBrowser.ts, libs/scully/src/lib/systemPlugins/writeToFs.plugin.ts, libs/scully/src/lib/utils/handlers/renderParallel.ts, libs/scully/src/lib/utils/log.ts, libs/scully/src/scully.ts, libs/scully/tsconfig.json, package.json
Make system plugins possible, using symbols.
internal plugins are set, and used directly
internal plugins will use pluginreposotory. They allow for symbols to be used as identifiers 
also first step to V10 support, by making tslib an direct dep.
=> feat(scully): system plugins

libs/ng-lib/src/lib/route-service/scully-routes.service.ts
If there are 2 routes with the same filname  but from different contentfolder, one of them gets removed.
Issue Number: closes #662
Only remove duplicates if they are really a duplicate (everything the same but the route, but if it's just a route, use the route)
=> fix(lib): make sure routes that are not duplicates are not filtered out of `available$`

libs/scully/src/lib/utils/config.ts, libs/scully/src/lib/utils/log.ts, libs/scully/src/scully.ts, package.json, tools/docker/chromium-base.dockerfile, tools/docker/pupeteer.dockerfile
=> feat(scully): killServers now works even when the config is not found

docs/plugins.md, docs/plugins_es.md, libs/scully/src/lib/renderPlugins/executePlugins.ts, libs/scully/src/lib/routerPlugins/addOptionalRoutesPlugin.ts, tests/jest/src/__tests__/__snapshots__/docsThere.spec.ts.snap
```
preRender(route.route, route.config)
```
```
preRender(route: HandledRoute)
```
for all adopters who already used `preRender`, they need to make a small tweak with parameters
=> feat(scully): provide full HandledRoute for preRender

docs/scully-configuration.md, tests/jest/src/__tests__/__snapshots__/docsThere.spec.ts.snap
- ~[ ] Tests for the changes have been added (for bug fixes / features)~
- typo fix
=> docs(scully-configuration): fix typo

libs/plugins/base-href-rewrite/package.json, libs/plugins/base-href-rewrite/src/lib/plugins-base-href-rewrite.ts
the plugin doesn't work outside our monorepo
Issue Number: closes #706
The plugin does work, by making sure it lists Scully as a peer dep, and not as a dep.
=> fix(monorepo): fix base-href-plugin to actually use existing scully, and not to bring it its won cop

docs/faq.md, tests/jest/src/__tests__/__snapshots__/docsThere.spec.ts.snap
There is an unexpected character in front of the first line of *Ignore routes without config?* FAQ (https://scully.io/docs/faq/)
Issue Number: #720 
There is a blank line before this line in order to detect the **>** character to render a blockquote tag
=> docs(faq): unexpected character

docs/scully-cmd-line.md, tests/jest/src/__tests__/__snapshots__/docsThere.spec.ts.snap
=> docs(scully): add docs for prod cli option

libs/scully/src/index.ts, libs/scully/src/lib/pluginManagement/index.ts, libs/scully/src/lib/pluginManagement/pluginWrap.ts, libs/scully/src/lib/renderPlugins/executePlugins.ts, libs/scully/src/lib/renderPlugins/puppeteerRenderPlugin.ts, libs/scully/src/lib/routerPlugins/traverseAppRoutesPlugin.ts, libs/scully/src/lib/systemPlugins/storeRoutes.ts, libs/scully/src/lib/utils/asyncPool.ts, libs/scully/src/lib/utils/cli-options.ts, libs/scully/src/lib/utils/handlers/defaultAction.ts, libs/scully/src/lib/utils/handlers/handleTravesal.ts, libs/scully/src/lib/utils/handlers/renderParallel.ts, libs/scully/src/lib/utils/handlers/routeDiscovery.ts, libs/scully/src/lib/utils/log.ts, libs/scully/src/lib/utils/serverstuff/handleUnknownRoute.ts, libs/scully/src/lib/utils/startup.ts, package.json
Most system plugins are not in the plugin repository
Issue Number: closes: #682 #683 #684 #685 #686 #677
all plugins are in the repository
@amycdurbin this closes entire epic #677
=> refactor(scully): move plugins to registery

libs/plugins/scully-plugin-flash-prevention/src/lib/flash-prevention.plugin.ts, libs/scully/package.json, tests/jest/src/__tests__/__snapshots__/docsThere.spec.ts.snap
Sometimes when use the flash-prevention the scroll event continue working after run angular
=> fix(lib): remove scroll event after angular load in flash prevention

libs/scully/package.json, libs/scully/src/lib/utils/handlers/defaultAction.ts
the original route list is used by Scully
Dont use the original routes, but the processed ones instead
- [x ] No
=> fix(scully): use processed routes instead of original ones

docs/getting-started.md, tests/jest/src/__tests__/__snapshots__/docsThere.spec.ts.snap
=> docs(schematics): add docs for angular workspace support

docs/faq.md, tests/jest/src/__tests__/__snapshots__/docsThere.spec.ts.snap
=> docs(docsWeb): add faq entry for plugin build error fix

apps/scully-docs/src/app/components/book/book.component.html, apps/scully-docs/src/app/components/book/book.component.ts, apps/scully-docs/src/app/landing/landing.component.css, apps/scully-docs/src/app/landing/landing.component.html, apps/scully-docs/src/styles.css, libs/scully/package.json, libs/scully/src/lib/utils/handlers/defaultAction.ts, tests/jest/src/__tests__/__snapshots__/docsThere.spec.ts.snap
Adds an href property to the component, so it redirects.
Improves the book component in the docs app. It also changes the landing components so they redirect to a proper url.
The book components in the landing page do not redirect.
Issue Number: #710 
The book components in the landing page redirect.
=> fix(docs): book component

docs/scully-configuration.md, libs/scully/src/lib/utils/interfacesandenums.ts, libs/scully/src/lib/utils/serverstuff/handleUnknownRoute.ts, libs/scully/src/lib/utils/serverstuff/staticServer.ts, tests/jest/src/__tests__/__snapshots__/docsThere.spec.ts.snap
=> feat(scully): add support for different folders to host to aid i18n

libs/scully-schematics/src/files/blog-module/blog.component.ts
There is unnecessary code inside the *BlogComponent* file generated with the blog support.
Issue Number: #746 
The boilerplate code is removed.
=> refactor(schematics): remove boilerplate

libs/scully-schematics/src/scully/index.ts
Documentation is right (https://scully.io/docs/scully-cmd-line/) for v1.0.0-beta.0, and says `--project ` as the right way to launch those 2 scripts.
- [x ] Bugfix
When adding scully capabilities (`ng add @scullyio/init`) to an existing Angular project (**not default project**) in a Nx mono-repo, when running `npm run scully`, it simply fails, because it tries to launch `scully --projectName=<projectName>`. Same for `npm run scully:serve`.
It works as expected.
- [ x] No
Tested on Angular 9.1.9 project on a Windows 10 machine.
=> (fix/schematics): package.json generated scripts

README.md
- [ x] Bugfix
Readme Links for Getting Started & Full Documentation are broken - linked to 404 error.
Issue Number: #830 
Getting Started & Full Documentation links now redirect to https://scully.io documentation
- [ x] No
=> docs: fixed broken links #830

libs/ng-lib/src/lib/transfer-state/transfer-state.service.ts
In some circumstances TSS doesn't produce the needed data
Also produce the data in those cirumstances
=> fix(lib): use transfer-state if there is a fragment or query param

libs/scully-schematics/src/add-post/index.ts, libs/scully-schematics/src/utils/utils.ts
Updating the inner workings of the schematics to not directly access the file system. Instead this uses the virtual file system built in to schematics.
=> refactor(schematics): Remove usage of the file system directly

apps/sample-blog/browserslist, apps/scully-docs/browserslist, libs/plugins/google-analytics/src/lib/plugins-google-analytics.ts, libs/plugins/logrocket/src/lib/plugins-logrocket.ts, libs/plugins/scully-plugin-remove-scripts/README.md, libs/plugins/scully-plugin-remove-scripts/src/lib/plugins-scully-plugin-remove-scripts.ts, libs/scully/src/lib/pluginManagement/pluginConfig.ts, scully.sample-blog.config.ts, scully.scully-docs.config.ts, workspace.json
Not all scripts are removed correctly
All scripts are removed correctly
=> fix(lib): removeScriptPlugn(fix) make sure _all_ scripts are removed

docs/learn/getting-started/installation.md, libs/scully/src/scully.ts
I encountered a basic typo issue with Windows Subsystem Linux short world.
Typo error.
=> style(schematics): fix typo wls to wsl

apps/scully-docs/src/app/app-routing.module.ts, apps/scully-docs/src/app/components/lang-select/component/lang-select/lang-select.component.ts, apps/scully-docs/src/app/components/nav-list/nav-list.service.ts, apps/scully-docs/src/app/components/nav-list/navitem.ts, apps/scully-docs/src/app/page-not-found.component.ts, apps/scully-docs/src/app/pages/docs/page/docs.page.component.ts, docs/overview_es.md, firebase.json
404 is handled unpredictable.
Spanish language files are not shown in docs-menu cirrectly
there is an actual 404 page that will be shown on non-exisiting pages
and the language files are shown as expected
Non existing pages in the docs will now show a 404 page instead of the index
=> fix(scully): feature(scully) add 404 handling

docs/Reference/command-line-options.md, docs/Reference/config.md, libs/scully/src/lib/utils/cli-options.ts, libs/scully/src/lib/utils/config.ts, libs/scully/src/lib/utils/log.ts, scully.scully-docs.config.ts
see #986 
documented behavior, added CLI option to override.
If you have a `logFileSeverity` setting in your config file, it now takes a type:
```typescript
export type LogSeverity = 'normal' | 'warning' | 'error' | 'none';
```
instead of an enum.
=> feat(scully): cmdLine option to set logSeverity

docs/concepts/handled-routes_es.md
=> docs: ✏️ add docs\concepts\handled-routes_es.md

libs/scully/src/lib/systemPlugins/storeRoutes.ts
in watch mode rotues are not written into the angular folder
Routes are written after an actual update, not if those are the same. Prevents the infinitive loop
=> feat(scully): only write routes in watch mode if they are updated

docs/Reference/legacy-support/overview.md, docs/Reference/ngLib/overview.md, docs/Reference/overview.md, docs/Reference/plugins/built-in-plugins/router-render.md, docs/Reference/plugins/custom-plugins/overview.md, docs/Reference/plugins/custom-plugins/register-a-new-plugin.md, docs/Reference/plugins/overview.md, docs/Reference/plugins/types/overview.md, docs/Reference/schematics/overview.md, docs/Reference/utilities/overview.md, docs/concepts/handled-routes.md, docs/concepts/handled-routes_es.md, docs/concepts/overview.md, docs/concepts/plugins.md, docs/concepts/process.md, docs/learn/create-a-blog/add-blog-support.md, docs/learn/create-a-blog/add-blog-support_es.md, docs/learn/create-a-blog/overview.md, docs/learn/create-a-blog/overview_es.md, docs/learn/getting-started/tips-for-testing.md, docs/learn/getting-started/tips-for-testing_es.md, docs/learn/introduction_es.md, docs/learn/overview.md, docs/learn/overview_es.md
Internal links for reference docs are broken.
https://scully.io/docs/Reference/overview/ on this page `NG Lib` and `Legacy Support` links are not working. The same issue is there for other documents.
One scenario I have marked is Internal Links which have `.md` at the end in the doc is not working.
Issue Number: 
Updated the internal links.
=> docs: fix broken internal links

libs/plugins/docs-link-update/src/lib/plugins-docs-link-update.ts
Hyperlinks for internal documents (`.md`) are not rendered properly. 
If we have link as `[NG lib](/docs/Reference/ngLib/overview.md)` in the markdown document file, then this link is transformed as `/docs/Reference//docs/Reference/ngLib/overview` in static HTML which creates the broken links.
Handle both relative and full path document link
For example, We can write `NG Lib` link in `/docs/Reference/overview.md` file as below,
- Link with full path `[NG lib](/docs/Reference/ngLib/overview.md)`  will be transformed as `/docs/Reference/ngLib/overview`.
- Link with relative path  `[NG lib](ngLib/overview.md)` will be transformed as `docs/Reference/ngLib/overview`
=> fix(scully): fix docs-link plugin

libs/scully/src/lib/utils/cli-options.ts
- `showGuessError` command description is mapped with `sb` (showBrowser)
- Alias `p` is mapped with two commands `path` and `port`.
- `showGuessError` description mapping is fixed.
- Alias `p` removed from `path`.
=> fix(scully): fix cli options showGuessError and path configuration

docs/learn/create-a-blog/generate-new-blog-posts.md, docs/learn/create-a-blog/generate-new-blog-posts_es.md, docs/learn/create-a-blog/use-blog-post-data-in-template.md, docs/learn/create-a-blog/use-blog-post-data-in-template_es.md
- In [Generating new blog posts](https://scully.io/docs/learn/create-a-blog/generate-new-blog-posts/) document scully serve command is specified as `npm run scully serve`, though this will work, but when we add scully in angular project we already provide `"scully:serve": "scully serve"` script in `package.json`, So instead of `npm run scully serve` command it should be the provided script command: `npm run scully:serve`.
- `ScullyRoute` interface now includes `lang` property, but In [Using blog data in an Angular template](https://scully.io/docs/learn/create-a-blog/use-blog-post-data-in-template/) document it is not specified.
- Updated scully serve command to `npm …
=> docs: update scully serve command and ScullyRoute interface

libs/scully/src/lib/utils/log.ts
No longer log ANSI escape codes from terminal styling to scully.log file
Issue #1010
See [issue](https://github.com/scullyio/scully/issues/1010) "ANSI escape codes from terminal styling logged to scully.log file"
Issue Number: 1010
ANSI escape characters are removed from strings before getting logged.
=> fix(scully): strip string styling escape characters when logging

apps/scully-docs/src/styles/toc.css
The table of content is not properly rendered on a large list of headings. as shown below 
Affected pages : [Command Line Options](https://scully.io/docs/Reference/command-line-options/) and [Scully Config](https://scully.io/docs/Reference/config/).
Updated CSS of TOC. It will now show a scroll bar for a large list.
=> fix: scully docs toc overflow issue

docs/faq.md, libs/scully/src/scully.ts
Scully fails with a strange error when used in Windows PowerShell on a path that has uppercase characters in it
Issue Number: closes #1000 
It tries to start a local instance, and errors out when that fails. 
So most of the time it will still work.
=> feat(scully): give error if start environment is off

docs/Reference/command-line-options.md
[Command Line Options](https://scully.io/docs/Reference/command-line-options/) doc includes the `highlight` flag, which is not used anywhere in code.
Scully uses `prism.js` and `md` plugin to render code snippets. `highlight.js` and `highlight` flag is not in use, the `highlight` flag might misguide the user.
Removed the highlight flag doc.
=> docs: remove cli options highlight flag doc

libs/plugins/scully-plugin-copy-to-clipboard/README.md, libs/plugins/scully-plugin-copy-to-clipboard/src/lib/plugins-scully-plugin-copy-to-clipboard.spec.ts, libs/plugins/scully-plugin-copy-to-clipboard/src/lib/plugins-scully-plugin-copy-to-clipboard.ts, scully.scully-docs.config.ts
It is PascalCase.
It should be camelCase to keep consistency.
=> refactor(lib): use camel case for copyToClipboard plugin

docs/Reference/plugins/types/router.md
In the example the config function is missing causing the plugin
to be invalid
Updating documentation 
In the documentation for a router plugin, the config function its not declared. And its 
Added the config function to the example
=> docs(scully): Add config function to the router plugin example

libs/plugins/scully-plugin-critical-css/README.md, libs/plugins/scully-plugin-critical-css/src/lib/plugins-scully-plugin-critical-css.ts
Hi! 
I'm not sure if this is a feature rather than anything else, please let me know if I need to change something.
It's not possible to pass `ignore` configuration to the `critical` tool (see https://github.com/addyosmani/critical#critical)
ignore configuration is documented in the plugin options interface and is passed to the critical tool
=> feat(monorepo): feat(critical) expose ignore settings in plugin configuration

docs/Reference/ngLib/overview.md, docs/Reference/ngLib/overview_es.md
https://scully.io/docs/Reference/ngLib/overview/
The above link should have a link to ScullyRoutesService. But instead of has the idle-monitor service two times. We need to fix that.
Issue Number: #1125 
The links have been fixed in english and spanish versions.
=> fix(docs): missing link

.github/workflows/new-project.yaml
Due to the TS update the location of Scully is changed a bit
use the new localtion
=> fix(monorepo): fix failing new app test on build

docs/Reference/plugins/types/allDone.md, docs/Reference/plugins/types/routeDiscoveryDone.md
The documentation for `allDone` and `routeDiscoveryDone` is minimal and somewhat confusing.
Issue Number: #1115 
The explanation for the `allDone` and `routeDiscoveryDone` plugins was minimal. This expands it a little bit and gives an example of how to create each type of plugin.
More information can easily be added if there are more specific examples of when to use the plugins, particularly `allDone`.
=> allDone and routeDiscoveryDone Documentation Update

CONTRIBUTING.md, docs/Reference/command-line-options.md, docs/Reference/config.md, docs/Reference/config_es.md, docs/Reference/plugins/community-plugins/minifyHtml.md, docs/Reference/plugins/community-plugins/minifyHtml_es.md, docs/faq.md, docs/faq_es.md, docs/learn/create-a-blog/add-blog-support.md, docs/learn/create-a-blog/add-blog-support_es.md, docs/learn/create-a-blog/generate-new-blog-posts.md, docs/learn/create-a-blog/generate-new-blog-posts_es.md, libs/scully/package.json, libs/scully/src/lib/fileHanderPlugins/markdown.ts, libs/scully/src/lib/utils/cli-options.ts, libs/scully/src/lib/utils/config.ts, libs/scully/src/lib/utils/interfacesandenums.ts, libs/scully/src/lib/utils/log.ts
When you use/import one of the log functions Scully starts to process the config file.
This makes it hard to write tests and is unneeded when just importing.
Also, an empty log file is created when log-severity none is given. (#1119) 
and a couple of warnings are raised because of misaligned 'prism' types
Issue Number: closes #1119
The logServirity config file option is removed(breaking change). Now it's only possible to set this option using the cmd-line.
Also, markdown files using 'prism' languages that are non-existent are updated, and if available the corresponding prism components are loaded.
The impact of the breaking change is very low, as the functionality is still there. As we …
=> fix(scully): fix config parsing when using logging

libs/scully/package.json, libs/scully/src/lib/renderPlugins/launchedBrowser.ts, libs/scully/src/lib/utils/config.ts, libs/scully/src/lib/utils/handlers/defaultAction.ts, libs/scully/src/lib/utils/serverstuff/handleUnknownRoute.ts, libs/scully/src/lib/utils/serverstuff/staticServer.ts, libs/scully/src/lib/watchMode.ts, libs/scully/src/scully.ts
Config was still compiled when importing from Scully. This can lead to unforeseen side-effect. especially while testing.
(eager promises are a thing... sigh)
Config is only compiled when Scully is running. Not when importing things.
=> fix(scully): fix premature compilation of the config

.vscode/launch.json, libs/scully/package.json, libs/scully/src/lib/startBackgroundServer.ts, libs/scully/src/lib/utils/cli-options.ts, libs/scully/src/lib/utils/exitHandler.ts, libs/scully/src/lib/utils/log.ts, libs/scully/src/scully.ts, testexit.js
When you load something out of Scully in library mode (not actually running any of the parts) the calling program will not exit naturally anymore.
Node will exit when Scully is used in 'library' mode
=> fix(scully): refactor to allow Scully to exit a process in library mode.

docs/Reference/plugins/community-plugins/page-title.md
docs: add page-title community plugin
Added the page title plugin to the community plugins section of the docs
Add the [page-title](https://npmjs.com/package/scully-plugin-page-title) plugin to the community plugin pages
=> page-title Community Plugin

libs/scully/src/lib/renderPlugins/launchedBrowser.ts
- [ x ] The commit message follows our guidelines: https://github.com/scullyio/scully/blob/main/CONTRIBUTING.md#commit
- [ x ] Bugfix
- [ x ] Feature
Traps error, calls `return launches.next();` but for this error, won't actually do anything.
Logs error to console, for easier debugging of a hung scully build.
- [ x ] No
=> feat(scully): throw trapped error if fatal puppeteer error around chomium location

docs/Reference/plugins/community-plugins/time-to-read.md
- [X ] Feature
This plugin will add an extra data property that people can use with the blog schematics and will say how much time an article cost to read it.
=> docs: add time-to-read plugin to the docs

docs/Reference/plugins/community-plugins/rss.md, libs/scully/src/lib/startBackgroundServer.ts, libs/scully/src/lib/utils/serverstuff/handleUnknownRoute.ts
- [ x ] The commit message follows our guidelines: https://github.com/scullyio/scully/blob/main/CONTRIBUTING.md#commit
- [ x ] Feature
It runs the puppeteer server in the background, without showing the command used to start.
It just outputs to the console the command used to start the server.  This is helpful for starting the server manually before build.  Node will see the server is started with the same command, and not start it again.  Instead all requests will be directed to your previously started server, and you can watch the logging or errors that are output from the server.  Otherwise there is no logging of those errors or output from the spawned process.
- [ …
=> Add logging for puppeteer server start cmd

docs/Reference/command-line-options.md, libs/scully/src/lib/startBackgroundServer.ts, libs/scully/src/lib/utils/cli-options.ts, libs/scully/src/scully.ts
Scully checks whether it's running from a Scully project folder and doesn't run if it can't find an installed copy of itself in `node_modules`. However this check fails when Scully is installed via symlinking such as when using a tool such as [pnpm](https://pnpm.js.org/) to manage multiple projects in a monorepo or when using `npm link` to install a locally modified copy of Scully into a test project during development. 
Scully supports a new CLI option `--disableProjectFolderCheck` which disables the project folder check. Aside from enabling symlinked installation, this change also enables running Scully from sub-directories or in projects with hoisted dependencies such as those …
=> feat(scully): add --disableProjectFolderCheck CLI option

docs/Reference/ngLib/transfer-state-service.md
Added description for `useScullyTransferState`. Additionally provided some information regarding the usage of TransferState with Angular Route Resolvers.
n/a
New docs as described.
=> docs(ng-lib): add useScullyTransferState description

demos/plugins/errorPlugin.js, demos/plugins/tocPlugin.js, docs/Reference/plugins/overview.md, docs/Reference/plugins/types/render.md, docs/Reference/plugins/types/render_es.md, docs/Reference/plugins/types/rendererDom.md, libs/plugins/base-href-rewrite/src/lib/plugins-base-href-rewrite.ts, libs/plugins/docs-link-update/src/lib/plugins-docs-link-update.ts, libs/plugins/google-analytics/src/lib/plugins-google-analytics.ts, libs/plugins/logrocket/src/lib/plugins-logrocket.ts, libs/plugins/scully-plugin-copy-to-clipboard/src/lib/plugins-scully-plugin-copy-to-clipboard.ts, libs/plugins/scully-plugin-critical-css/src/lib/plugins-scully-plugin-critical-css.ts, libs/plugins/scully-plugin-flash-prevention/src/lib/flash-prevention.plugin.ts, libs/plugins/scully-plugin-remove-scripts/src/lib/plugins-scully-plugin-remove-scripts.ts, libs/plugins/sentry/src/lib/plugins-sentry.ts, libs/scully-schematics/src/add-plugin/schema.ts, libs/scully-schematics/src/files/plugin/render/__name@dasherize__.plugin.js.template, libs/scully-schematics/src/plugin-ts/index.ts, libs/scully/src/lib/pluginManagement/Plugin.interfaces.ts, libs/scully/src/lib/pluginManagement/pluginRepository.ts, libs/scully/src/lib/pluginManagement/pluginWrap.ts, libs/scully/src/lib/renderPlugins/contentRenderPlugin.ts, libs/scully/src/lib/renderPlugins/contentTextRenderPlugin.ts, libs/scully/src/lib/renderPlugins/executePlugins.ts, libs/scully/src/lib/renderPlugins/seoHrefCompletionPlugin.ts, releaseChecksums.json, scully.scully-docs.config.ts, scully/plugins/error.ts
Renderer plugins are now renamed to postProcessbyHtml and using the old name will display a deprecation warning.
=> feat(scully): rename renderer to postProcessByHtml and add postProcessByDom

libs/scully-schematics/src/scully/index.ts
After we run the build/serve script, it will get an error like the following:
```
$ npm run scully
> scully@0.0.0 scully /Users/leo/Documents/Angular小聚/2021/scully
> npm scully --
Usage: npm <command>
where <command> is one of:
access, adduser, audit, bin, bugs, c, cache, ci, cit,
clean-install, clean-install-test, completion, config,
create, ddp, dedupe, deprecate, dist-tag, docs, doctor,
edit, explore, fund, get, help, help-search, hook, i, init,
install, install-ci-test, install-test, it, link, list, ln,
login, logout, ls, org, outdated, owner, pack, ping, prefix,
profile, prune, publish, rb, rebuild, repo, restart, root,
run, run-script, s, se, search, set, shrinkwrap, star,
stars, …
```
=> fix(schematics): fix the scripts in package.json

libs/scully-schematics/src/scully/index.ts
Before:
` jsonContent.scripts.scully = 'npm scully --' + params;`
After:
` jsonContent.scripts.scully = 'npx scully --' + params;`
=> fix: fix scripts.scully script to use npx instead of npm

docs/concepts/unhandled-routes.md
The router example above the traversed unhandled routes, uses :userId as a variable instead of :id.
- [x ] The commit message follows our guidelines: https://github.com/scullyio/scully/blob/main/CONTRIBUTING.md#commit
- [x ] Refactoring (no functional changes, no api changes)
- [ x] No
=> docs: adjust the unhandled routes to use userId

docs/Reference/config.md, libs/scully/src/lib/utils/config.ts, libs/scully/src/lib/utils/interfacesandenums.ts
Currently if you change `architect` to `targets` in workspace.json the scully build will fail.
Issue Number: https://github.com/scullyio/scully/issues/1394
You can now optionally add a new configuration item called `target` to specify what target scully should use for the build.
=> feat(scully): Add config property for architect target

docs/Reference/plugins/built-in-plugins/json.md, libs/scully/src/lib/utils/httpGetJson.ts, libs/scully/src/lib/utils/interfacesandenums.ts
Passing `Content-Type` in route headers is not being considered in `httpGetJson` method. This restricts developers to stick to `application/json` type only.
httpGetJson method now checks whether `content-type` matches with specified `Content-Type` in headers passed in scully config file. If not specified, then it compares content types by default to `application/json`.
Resubmitting https://github.com/scullyio/scully/pull/1405 since I had no proper email attached to branch commits required to sign CLA.
=> feat(scully): consider Content-Type passed in headers in httpGetJson

docs/Reference/plugins/types/router.md
The second code snippet on
https://scully.io/docs/Reference/plugins/types/router/ page is incorrect
for two reasons. Firstly, the snippet is marked as 'Javascript' but it's
strongly typed (uses Typescript) and secondly the 'HandledRoute' is
missing. Change the marked language and update the imports
accordingly.
BREAKING CHANGE:  None
The second code snippet on
https://scully.io/docs/Reference/plugins/types/router/ page is incorrect
for two reasons. Firstly, the snippet is marked as 'Javascript' but it's
strongly typed (uses Typescript) and secondly the 'HandledRoute' is
missing.
The marked language is now set to 'Typescript and the import section has been updated …
=> docs(scully): fix documentation snippet on router plugin type page

libs/scully/src/lib/utils/compileConfig.ts
Current users who have a space in their path for example
`C:\Users\Evan Johnson\source\repos\samplerepo` are unable to run scully without manually editing the node package.
In order to fix this I have added "" around the path in the command.
Issue Number: 
fixes #1425 
Allow scully commands to work for windows users whose path contain spaces.
=> Fix Windows parent folder with space

libs/scully/src/lib/utils/serverstuff/staticServer.ts, libs/scully/src/lib/utils/startup/startBackgroundServer.ts
This will forcefully kill the background server when scully is done processing
ISSUES CLOSED: #1513
=> fix(scully): kill background server on exit

.github/module-cache/action.yaml, .github/workflows/workflow.yml, package-lock.json, package.json
=> fix(monorepo): update package-lock to not fail on install.

docs/concepts/unhandled-routes.md, docs/faq.md
Clarification on query strings and parameterized routes
Missing information on query strings / parameters and dynamic routes. 
Adding additional information on the subject of query strings / parameters and Angular parameterized routes to the Q & A section to assist others. Updated Angular routes title to include Parameterized to hopefully directly route future searchers to the appropriate information.
=> docs(scully): additional query parameter info

libs/plugins/scully-plugin-playwright/src/lib/plugins-scully-plugin-playwright.ts, libs/plugins/scully-plugin-puppeteer/src/lib/plugins-scully-plugin-puppeteer.ts
Since version 0.11.5 Zone.Js [patches all window properties started from `on` prefix](https://github.com/angular/angular/blob/0f298a13dbd141e5440d1388b124d03384641efe/packages/zone.js/lib/browser/property-descriptor.ts#L51). Puppeteer plugin uses `onRenderReady` event to notify puppetteer.  So Zone patching makes impossible for puppeteer to receive such event, which causing to always wait for default 25sec timeout on Scully build for Angular projects.
Puppeteer doesn't always wait for timeout and processes correctly.
One can suppress Zone patching of the `onRenderReady` event in the projects manually, but it would be great to have solution working out-of-the-box. And …
=> fix(scully-plugin-puppeteer): rename `onRenderReady` event to prevent zone.js patching

libs/scully/src/lib/routerPlugins/traverseAppRoutesPlugin.ts
Displays a message which does not work if `"scully": "npx scully"` is not part of `package.json`.
Now the command works for all cases
=> style(scully): Change logging to increase clarity

libs/plugins/scully-plugin-puppeteer/src/lib/plugins-scully-plugin-puppeteer.ts
Previously, instead of adding/removing each request from the `requests` set, the set itself was added/removed. Since `Set` deduplicates its values, it would always contain just one item (regardless of how many requests would be pending) and it would be emptied once the first request was completed.
This commit fixes this by adding/removing the actual request to/from the `requests` set.
=> fix(scully-plugin-puppeteer): correctly track requests in bare project
