- LICENSE
> feat(LICENCE): add MIT LICENSE

- schematics/scully/package-lock.json
- schematics/scully/package.json
- schematics/scully/src/files/blog-module/blog-routing.module.ts
- schematics/scully/src/files/markdown-module/__name@dasherize__-routing.module.ts.template
remove heroRoute for the basic config
> schematics(remove): remove heroRoute for the basic config

- schematics/scully/src/ng-add/index.ts
> Fix ng-add to allow to be ran multiple times

- .github/ISSUE_TEMPLATE/---bug-report.md
- Add minor changes in bug report file
- Add the first version of a feature request.
> refactor(docs):  bug report and  feature request

- docs/blog.md
Minor typo changing the word 'you' to 'your'
> Updated blog.md

- .github/ISSUE_TEMPLATE/---bug-report.md
> Remove whitespace in bug report template

- README.md
Fixes a few typos in README.md.
> README.md typo fixes

- scully/readme.md
- Add section "Office Hours" to readme.md.
- Fix path HeroDevs logo.
> docs(scully): add office hours information to NPM

- docs/getting-started.md
make it easier for beginners to start with
> docs(scully): put link to set up angular project & note  needed chromium support

- docs/getting-started.md
- docs/issues.md
- docs/pre-requisites.md
- docs/scully-configuration.md
- docs/scully.md
- scully/utils/config.ts
Fixed some types/things in the docs.
> docs: fix typos/update docs

- README.md
- docs/scully.md
> docs(scully): add link to Gitter in the docs

- docs/plugins.md
- docs/scully.md
> refactor(docs): Add extra information about plugins.

- README.md
- docs/scully.md
why? because I missed it in my first PR and probably made it wrong
Please make easier contribution guidelines for docs changes. ❤️ 
At the end it is just a change of markdown. I don't want to do 100 things to change a spelling mistake.
> docs(scully): add link to contribution guidelines

- docs/plugins.md
> docs(scully): fix code styling

- README.md
> docs(scully): update office hours info

- README.md
- scully/readme.md
> docs(scully):  update readme.md to NPMJS

- CONTRIBUTING.md
- README.md
- scully/readme.md
> docs(scully): add right link to sign CLA

- scully/utils/compileConfig.ts
- scully/utils/defaultAction.ts
no warnings
Warnings are being reased when needed
- [x ] No
> Add warnings

- docs/scully.md
> docs(scully): fix link to CONTRIBUTING.md file

- docs/plugins.md
- docs/scully-configuration.md
- docs/scully.md
- docs/utils.md
Add details about: 
- `scully.config.js`
- Plugins.
> docs(scully): add content about scully.config and plugins

- schematics/scully/src/ng-add/index.ts
add support for angular v8 library
> feat(ng-add): add support for angular v8

- schematics/scully/package-lock.json
- schematics/scully/package.json
- schematics/scully/src/ng-add/index.ts
> fix(ng-add): fix error in regex into ngadd

- schematics/scully/src/ng-add/index.ts
- schematics/scully/src/utils/utils.ts
> fix: 🐛 fix install error, double slash and run

- projects/scullyio/ng-lib/src/lib/route-service/scully-routes.service.ts
Unused import from non-mapped path.
No import.
> fix(ng-lib): remove failing import

- schematics/scully/package-lock.json
- schematics/scully/package.json
- schematics/scully/src/scully/index.ts
> feat(scullyindex): add outfolder for support config into scully.config

- docs/scully-configuration.md
- scully.config.js
- scully/package.json
- scully/renderPlugins/puppeteerRenderPlugin.ts
- scully/scully.ts
- scully/utils/config.ts
- scully/utils/fsAngular.ts
- scully/utils/httpGetJson.ts
- scully/utils/interfacesandenums.ts
- scully/utils/staticServer.ts
- scully/utils/waitForServerToBeAvailable.ts
- scully/watchMode.ts
on some computers, localhost isn't avaialble. This pr takes care of that by making the name to be
used an setting
closes #87
Currently `localhost` is hardcoded in a number of places
the hostName is now an optional setting in scully.config
> feat(hostname): puts in a hostname option

- docs/CODE_OF_CONDUCT.md
- docs/plugins.md
- docs/scully-configuration.md
- [ x] The commit message follows our guidelines: https://github.com/scullyio/scully/blob/master/CONTRIBUTING.md#commit
- [ x] Docs have been added / updated (for bug fixes / features)
- [x ] Other... Please describe: fix some typos in documentation.
Just some missing letters in some words in the docs.
N/A
- [ x] No
> docs: ✏️ fix some typos found in docs

- schematics/scully/src/create-markdown/index.ts
- schematics/scully/src/utils/utils.ts
> fix(create-markdown): filter non ASCII characters

- extraPlugin/extra-plugin.js
- extraPlugin/tocPlugin.js
- extraPlugin/voidPlugin.js
> fix(js plugins): update to use new register function

- .github/ISSUE_TEMPLATE/---bug-report.md
use correct command for `ng --version`
> chore(scully): fix command in ISSUE_TEMPLATE

- schematics/scully/src/utils/utils.ts
> fix(create-markdown): add more chars to support

- schematics/scully/src/scully/index.ts
> fix(scully-index): change outFolder for outDir

- schematics/scully/src/scully/index_spec.ts
> test(schematics): use `outDir` instead of `outFolder`

- scully/index.ts
Currently the `scullyConfig` needs to be imported from`@scullyio/scully/utils/config`.
With the change we can import the `scullyConfig` from `@scullyio/scully`
> chore(config): exported scullyConfig

- docs/recommended-plugins.md
Updated the documentation:
- specify type of plugin
- add 2 community plugins with their type
No new behavior
> docs(scully): update official & community plugins

- docs/scully-cmd-line.md
- docs/scully.md
> docs(scully): minor fixes

- docs/recommended-plugins.md
> docs(scully): update information about official plugins

- schematics/scully/src/add-blog/index.ts
Fix a typo in the add-blog schematics
> refactor(schematics): fix typo for markdown

- .github/ISSUE_TEMPLATE/----docs-report.md
- .github/ISSUE_TEMPLATE/---bug-report.md
- .github/ISSUE_TEMPLATE/---feature-request.md
> chore(scully): fix ISSUE_TEMPLATEs

- docs/scully-configuration.md
- docs/scully-lib-core.md
- docs/scully.md
Docs: Add explanation about Core components in ng-lib
> docs(scully): add docs about ng-lib

- .github/ISSUE_TEMPLATE/----docs-report.md
- .github/ISSUE_TEMPLATE/---bug-report.md
- .github/ISSUE_TEMPLATE/---feature-request.md
Docs: 
Fix error in issue template metadata. 
> docs(scully): fix emoji in issues template metada

- scully/fileHanderPlugins/asciidoc.ts
- scully/fileHanderPlugins/markdown.ts
- scully/pluginManagement/pluginRepository.ts
- scully/renderPlugins/content-render-utils/handleFile.ts
- scully/renderPlugins/contentRenderPlugin.ts
- scully/renderPlugins/launchedBrowser.ts
- scully/utils/defaultAction.ts
- scully/utils/performanceIds.ts
- scully/utils/startup.ts
crude start-stop total of the complete run
Fine-grained  statistics gather metrics for every plugin for every route separately.
> feat(performance statistics): gather performance statistics

- projects/scullyio/ng-lib/package.json
- scully/package.json
> chore(version update): version update

- projects/scullyio/ng-lib/package.json
- scully.sampleBlog.config.js
- scully/package-lock.json
- scully/package.json
> chore(limit)

- docs/getting-started_es.md
Getting started spanish translation updated
> docs(scully): update cli version on spanish translation

- docs/getting-started.md
updates the instructions to reflect the release of angular v9 removing the `@next` tag
Docs update
> docs(scully): update cli version

- scully/utils/cli-options.ts
> improvement(cmd): add alias for proxy

- .github/workflows/nodejs.yml
- scully/package-lock.json
- scully/package.json
add new function into the action
> ci(nodejs.yml): add pull request to run github actions

- scully/routerPlugins/addOptionalRoutesPlugin.ts
> fix: HandledRoute type is string

- package-lock.json
- package.json
- projects/scullyio/ng-lib/package.json
- scully/package-lock.json
- scully/package.json
> new version to npm

- docs/scully-cmd-line.md
- scully/routerPlugins/traverseAppRoutesPlugin.ts
- scully/utils/cli-options.ts
- scully/watchMode.ts
> Add better docs to `--scanRoutes`

- projects/sampleBlog/src/app/app.module.ts
- projects/scullyio/ng-lib/src/lib/config/scully-config.ts
- projects/scullyio/ng-lib/src/lib/idleMonitor/idle-monitor.service.ts
IdleMonitor only runs when rendering.
option in config to allways run the ideMonitor
> switchable IdleMonitor

- projects/scully-plugin-flash-prevention/README.md
> docs(lib): install plugin as dev dependency

- src/__tests__/flash-prevention.spec.ts
Test was testing the same thing twice. Updated to test the mock.
> test(lib): fix a test

- projects/scullyio/ng-lib/src/lib/idleMonitor/idle-monitor.service.ts
> refactor(lib): fix typo

- docs/recommended-plugins.md
> Update recommended plugins

- docs/recommended-plugins.md
Documentation update
Adds Gammastream's Scully plugins to the list of community plugins.
> docs(scully): add gammastream plugins to community plugins

- .vscode/settings.json
- projects/scullyio/ng-lib/package.json
- scully/package.json
> chore(monorepo): new versions

- docs/recommended-plugins.md
> docs(scully): add fouc and lazyImages plugins

- package.json
- projects/scullyDocs/src/assets/scully-routes.json
- projects/scullyDocs/src/docs/doc-page/doc-page.component.html
- projects/scullyDocs/src/docs/docs.component.html
- projects/scullyDocs/src/styles.css
> style(docsWeb): add css for docs

- projects/sampleBlog/src/app/app.module.ts
- projects/scullyDocs/src/app/app.module.ts
- projects/scullyio/ng-lib/src/lib/config/scully-config.ts
- projects/scullyio/ng-lib/src/lib/idleMonitor/idle-monitor.service.ts
- scully/utils/interfacesandenums.ts
> refactor: transfer state

- schematics/scully/src/files/blog-module/blog.component.css
- schematics/scully/src/files/markdown-module/__name@dasherize__.component.css.template
> fix(css): remove slotted pseudo-element

- projects/scullyDocs/src/app/components/code/code.component.ts
> fix(docsWeb): add a default value for code block

- scully/watchMode.ts
Issue Number: #379 
Now Ctrl+C close the watchmode
> fix(scully): WATCHMODE: fix problem when use CTRL+C

- docs/plugins.md
ISSUES CLOSED: 367
Issue Number: #367
> fix(docsWeb): pLUGIN: remove plugin example

- docs/CODE_OF_CONDUCT.md
add a code of conduct
ISSUES CLOSED: 322
Issue Number: #322
> feat(monorepo): CODE OF CONDUCT

- projects/scullyDocs/src/app/landing/landing.component.html
- projects/scullyDocs/src/assets/scully-routes.json
- projects/scullyDocs/src/styles.css
ISSUES CLOSED: 395
Issue Number: #395
> fix(docsWeb): fix line height in header title and subheader width text

- package-lock.json
- projects/scullyDocs/src/assets/scully-routes.json
- schematics/scully/package-lock.json
> fix(monorepo): upgrade dev dependencies

- projects/scullyDocs/src/app/app.component.html
> docs(docsWeb): fix Gitter typo in footer.

- docs/getting-started_es.md
Updates the spanish version of the getting started markdown
> docs(docsWeb): update the spanish version of getting started

- scully/utils/handlers/routeDiscovery.ts
`Problem during route handling, se below for details`
`Problem during route handling, see below for details`
> fix(scully): typo on error

- projects/scullyDocs/src/app/components/button/button.component.ts
- projects/scullyDocs/src/assets/scully-routes.json
when using keyboard navigation in docs head menu every button takes 2 stops
Issue Number: closes #454 
works as expected
> fix(docsWeb): fix double focus on keyboard event

- docs/showcase.md
- [x ] The commit message follows our guidelines: https://github.com/scullyio/scully/blob/master/CONTRIBUTING.md#commit
- [ x] Other... Please describe: Documentation
I have added ConfigCat link and logo to showcase.md
> adding configcat to showcase

- docs/getting-started_es.md
- docs/pre-requisites_es.md
Issue Number: #456
* Adds the Spanish translation of the current version of the pre-requisites.md file. 
* Updates Spanish getting started and adds a link to the Spanish pre-requisites page
> docs(scully): add spanish translation of the pre-requisites file and update getting started

- scully.scullyDocs.config.js
The docs site failed to build with this require failing.
> fix(docsWeb): change plugin require path to match file structure changes

- package.json
The docs:run command currently fails since the recent project name change.
> fix(docsWeb): change docsSite to scullyDocs in docs:run command

- scully/scully.ts
After sending the kill command to the server (`npm run scully killServer`), `Sended kill command to server` is logged in the console.
After sending the kill command to the server (`npm run scully killServer`), `Sent kill command to server` is logged in the console.
> style(scully): change 'Sended kill command to server' to 'Sent kill command to server'

- scully/renderPlugins/puppeteerRenderPlugin.ts
Issue Number:closes #490
read the package.json just ones every run.
> feat(scully): cache the version number during rendering

- schematics/scully/src/files/markdown-module/__name@dasherize__.component.spec.ts.template
Issue Number: #500 
fix dasherize function
> fix(schematics): fix wrong import into markdown spec

- docs/showcase.md
- [ x] The commit message follows our guidelines: https://github.com/scullyio/scully/blob/master/CONTRIBUTING.md#commit
- [ x] Other... Please describe: 
added my blog to showcase
- [ x] No
> docs(showcase): added my blog to showcase

- docs/getting-started.md
**Extra credits** at the bottom had a spelling error: sing -> using.
> docs(scully): fix spelling error

- ng-projects/scullyDocs/src/app/landing/landing.component.html
> docs(docsWeb): fix typo into home

- docs/getting-started.md
Just to make it more readable here - https://scully.io/docs/getting-started
First time I missed the command (when it was only in header)
> Docs style fix

- docs/blog.md
- typo
- typo fixed and now there is link to the prismjs utility
> docs(blog): fix typo and add link to prismjs utility

- docs/showcase.md
hello, I would be so happy to be able to add my portfolio written with Scully in your showcases 😀
new showcase in the showcase page
> Added new showcase

- libs/scully-schematics/package-lock.json
- libs/scully-schematics/package.json
- libs/scully-schematics/src/utils/utils.ts
> refactor(schematics):

- docs/showcase.md
- arrange icons and descriptions in table for better overview
- add website d-koppenhagen.de
> docs: update showcase site

- libs/scully/src/lib/systemPlugins/storeRoutes.ts
> feat(scully): work when whatch mode in scully and on ng build are both enabled

- libs/scully/src/lib/renderPlugins/launchedBrowser.ts
> fix(scully): add log error and exit with puppetter have some error

- docs/getting-started.md
> docs(typo): fix typo

- CHANGELOG.md
- libs/scully/src/lib/utils/config.ts
- libs/scully/src/lib/utils/log.ts
There is a typo into the *LogSeverity* enum : `waring`
renamed to `warning`
> fix(lib): typo on logs

- docs/plugins.md
Add new documentation.
Issue Number: #595
> docs(plugins): add better docs for defaultPostRenderers and postRenderers

- docs/features.md
- docs/getting-started.md
- docs/plugins.md
- docs/scully-configuration.md
Lot of links across scully documentation are broken
The broken links in scully documentation are fixed and works now
> docs: fix the broken links

- demos/plugins/docs-link-update.js
> fix(scully): fix rewrite of .md on external sites

- libs/scully-plugin-flash-prevention/src/lib/flash-prevention.plugin.ts
> feat(lib): raise an event when the switch is done by the FlashPreventionPlugin

- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
- README.md
- apps/scully-docs/src/app/app.component.html
- docs/release-for-v8.md
- docs/scully-cmd-line.md
- docs/showcase.md
- libs/ng-lib/package.json
- libs/plugins/base-href-rewrite/package.json
- libs/scully-schematics/package.json
- libs/scully/package.json
- workspace.json
> refactor(monorepo): updates for main branch

- docs/recommended-plugins.md
- docs/recommended-plugins_es.md
> docs(plugins): add rss and medium zoom plugin

- .github/workflows/publish.yml
- firebase.json
- package.json
> feat(docsWeb): add firebase deploy into the CI/CD

- libs/ng-lib/src/lib/route-service/scully-routes.service.ts
> fix(lib): drop opening `/` from assets link to follow base-href

- libs/plugins/scully-plugin-flash-prevention/src/lib/flash-prevention.plugin.ts
> fix(lib): fix flash prevention for support ie (remove arrow functions)

- libs/scully-schematics/package-lock.json
- libs/scully-schematics/package.json
- libs/scully/src/lib/utils/cli-options.ts
> fix(CLI-OPTIONS): fix --help

- apps/scully-docs/src/app/components/book/book.component.ts
- libs/plugins/logrocket/README.md
No readme file for LogRocket render plugin
Adds a proper readme file to the LogRocket render plugin
> fix(lib): add proper readme

- libs/scully/src/lib/pluginManagement/index.ts
- libs/scully/src/lib/pluginManagement/pluginConfig.ts
- libs/scully/src/lib/renderPlugins/executePlugins.ts
- libs/scully/src/lib/routerPlugins/addOptionalRoutesPlugin.ts
- libs/scully/src/lib/utils/handlers/routeDiscovery.ts
- libs/scully/src/lib/utils/interfacesandenums.ts
- libs/scully/tsconfig.json
- scully.sample-blog.config.ts
> fix(scully): add symbol support for plugins in places where ti was missing

- libs/scully/src/lib/pluginManagement/pluginRepository.ts
Remove the eslint deactivation as there is no more explicit any mention with #736 changes
The linter rule 'no explicit any' is deactivated.
The rule isn't deactivated anymore.
> refactor(lib): remove eslint deactivation

- apps/scully-docs/src/styles.css
- tests/jest/src/__tests__/__snapshots__/docsThere.spec.ts.snap
the dash of 'language-' prefix on app-code titles is partially visible.
Issue Number: #718 
The dash is hidden.
this PR removes duplicate border-radius duplicate style
> docs: hide dash on app-code title

- apps/scully-docs/src/app/components/card/card.component.css
- apps/scully-docs/src/app/components/card/card.component.html
- apps/scully-docs/src/app/landing/landing.component.css
- apps/scully-docs/src/styles.css
- tests/jest/src/__tests__/__snapshots__/docsThere.spec.ts.snap
The content of the feature card on the lading page of http://scully.io is partially hidden depending on the screen size.
Issue Number: #711
The content of these feature card si always fully visible.
> docs: landing page feature card on small screens

- docs/CONTRIBUTING.md
- docs/scully.md
- docs/scully_es.md
- tests/jest/src/__tests__/__snapshots__/docsThere.spec.ts.snap
> Fix missing contribute link

- libs/plugins/google-analytics/src/lib/plugins-google-analytics.ts
- tests/jest/src/__tests__/__snapshots__/blog-index.spec.ts.snap
- tests/jest/src/__tests__/__snapshots__/docsThere.spec.ts.snap
- tests/jest/src/__tests__/__snapshots__/home.spec.ts.snap
- tests/jest/src/__tests__/__snapshots__/route404.spec.ts.snap
- tests/jest/src/__tests__/__snapshots__/users.spec.ts.snap
- tests/jest/src/test-config.helper.ts
> fix(docsWeb): fix google analytics

- libs/ng-lib/package.json
- libs/plugins/docs-link-update/package.json
- libs/plugins/extra/package.json
- libs/plugins/from-data/package.json
- libs/plugins/scully-plugin-flash-prevention/package.json
- libs/plugins/scully-plugin-remove-scripts/README.md
- libs/plugins/scully-plugin-remove-scripts/package.json
- libs/scully-schematics/package.json
- libs/scully/README.md
- libs/scully/package.json
Issue Number:  #795 
@jorgeucano can you push all affected packages to a new beta version? There are some fixes I landed in the last week that warrant a new beta drop anyway.
> fix(monorepo): update links in package.json

- libs/scully/src/lib/renderPlugins/launchedBrowser.ts
- libs/scully/src/lib/testData/users-testdata.ts
- scully.sample-blog.config.ts
- tests/jest/src/__tests__/__snapshots__/home.spec.ts.snap
- tests/jest/src/__tests__/__snapshots__/users.spec.ts.snap
- tests/jest/src/__tests__/extra-users.spec.ts
If there are more than 500 routes rendered, when this limit is reached
a new browser instance is spawned. The async jobs rendering the
routes at that moment in the initial browser instance are not waited
and thus they are failing with exception and cause the process to stop.
The fix adds a delayWhen in the pipe which fires immediately if there is
no browser instance to wait for or after a 15 second delay if there was 
a browser instance running and probably some tabs are still rendering
asynchronously.
Update and add testserver data for 500+ routes.
Update test server to hold and serve 501 users.
Update snapshots for the newly added users
Add test to check for the extra rendered routes.
What kind of change does this PR …
> fix(scully): Add wait time before spawning new browser instance

- libs/plugins/extra/src/lib/plugins-extra.ts
- libs/plugins/from-data/src/lib/plugins-from-data.ts
- libs/scully/src/lib/fileHanderPlugins/html.ts
- libs/scully/src/lib/pluginManagement/Plugin.interfaces.ts
- libs/scully/src/lib/pluginManagement/pluginRepository.ts
- libs/scully/src/lib/routerPlugins/defaultRouterPlugin.ts
- libs/scully/src/lib/routerPlugins/handledRoute.interface.ts
- libs/scully/src/lib/routerPlugins/ignoredRoutePlugin.ts
configValidator gets HandledRoute, where it should have RouteCOnfig
Issue Number: clsoes #810 
It now uses the correct type for configValidator.
Also extended the registerplugin interface o be more precise on the needed parameters
> feat(scully): address wrng type in configValidator

- .gitignore
- libs/scully/src/lib/utils/compileConfig.ts
- [ x] The commit message follows our guidelines: https://github.com/scullyio/scully/blob/main/CONTRIBUTING.md#commit
> feat(scully): better message on project not found

- docs/community/showcase.md
- tests/assets/blog-files/page-6.md
- tests/jest/src/__tests__/__snapshots__/blog-index.spec.ts.snap
- tests/jest/src/__tests__/__snapshots__/docsThere.spec.ts.snap
- tests/jest/src/__tests__/__snapshots__/home.spec.ts.snap
- tests/jest/src/__tests__/blog-index.spec.ts
> fix(monorepo): fix test to remove double page-4

- libs/scully/src/lib/fileHanderPlugins/markdown.ts
Markdown plugin does not support JSX/TSX.
Issue Number: #548
It supports them.
Closes #548
> feat(scully): support JSX/TSX highlighting (#548)

- libs/scully/package.json
> Fix node-run '/r'

- libs/scully-schematics/src/collection.json
- libs/scully-schematics/src/ng-add/index.ts
- libs/scully-schematics/src/ng-add/schema.json
- libs/scully-schematics/src/ng-add/schema.ts
- libs/scully-schematics/src/ng-add/version-names.ts
- libs/scully-schematics/src/plugin-ts/index.ts
- libs/scully-schematics/src/plugin-ts/index_spec.ts
- libs/scully-schematics/src/plugin-ts/schema.json
- libs/scully-schematics/src/plugin-ts/schema.ts
- libs/scully-schematics/src/utils/utils.ts
Issue Number: #833 #834 #835 #836 
Add full support for custom typescript plugins
> Schematics: Support custom ts plugins

- libs/scully/.npmrc
- libs/scully/package.json
- package-lock.json
- workspace.json
Limit node version to 12 and up.
No more accepting node V10.
> feat(scully): limit scully to node 12 and up

- libs/scully/src/lib/renderPlugins/puppeteerRenderPlugin.ts
> fix(scully): fix message error when need retry other times is a warning

- docs/learn/plugins/overview.md
- docs/learn/plugins/register-a-new-plugin.md
- tests/jest/src/__tests__/__snapshots__/docsThere.spec.ts.snap
N/A
Issue Number: #666 
Adds Plugin System documentation
> Docs plugin system

- docs/learn/plugins/built-in-plugins/md.md
- tests/jest/src/__tests__/__snapshots__/docsThere.spec.ts.snap
How to enable the highlight option on md plugin
- [x ] The commit message follows our guidelines: https://github.com/scullyio/scully/blob/main/CONTRIBUTING.md#commit
- [ x] Docs have been added / updated (for bug fixes / features)
- [ x] Other... Please describe:
improve docs for md plugin.
md plugin page without detailed description
add description on how to use the highlight option. 
- [x ] No
> docs(md): add prismjs usage

- docs/concepts/overview.md
- docs/concepts/process.md
- docs/learn/getting-started/building.md
- docs/learn/getting-started/installation.md
- docs/learn/getting-started/requirements.md
- docs/learn/introduction.md
- tests/jest/src/__tests__/__snapshots__/docsThere.spec.ts.snap
> docs(monorepo): first update docs

- docs/concepts/overview.md
- tests/jest/src/__tests__/docsThere.spec.ts
Docs markdown files are not tested for title or lang attribute
A test is added to check the validity of both attributes in the front-matter part
Also, it's optimized to read the markdown file just once instead of 4 times.
> test(monorepo): add title and language attribute testing to docs files

- docs/learn/config.md
- docs/learn/create-a-blog/overview.md
- docs/learn/plugins/community-plugins/minifyHtml.md
- package-lock.json
- package.json
- tests/jest/src/__tests__/docsThere.spec.ts
links in the markdown test are not tested
All links in the markdown files are checked. No more dead links in the docs.
It is not longer possible to merge docs that have broken links
The downside of testing all the links is that fetching the external URL's adds 17 seconds to the test run.
> test(docsWeb): test all links in markdown files to exist.

- .github/workflows/nodejs.yml
- nx.json
- package-lock.json
- package.json
>  Add nx cloud build 

- .github/workflows/cache.yml
- .github/workflows/nodejs.yml
- .github/workflows/publish.yml
- .prettierignore
> Add cache Github Actions

- libs/scully-schematics/src/ng-add/index.ts
> change text into schematics for install ng-lib

- docs/community/sponsors.md
- docs/faq.md
> docs(docsWeb): add docker, distFolder and Sponsors to docs

- .github/workflows/cache.yml
- .github/workflows/nodejs.yml
- .github/workflows/publish.yml
> remove npm i from GA in pull request

- .github/workflows/publish.yml
> fix cache issue in ga

- docs/faq.md
> docs(scully): typo in FAQ

- apps/scully-docs/src/app/pages/docs/page/docs.page.component.ts
- apps/scully-docs/src/index.html
- docs/Reference/config.md
- docs/Reference/plugins/built-in-plugins/contentFolder.md
- docs/Reference/plugins/built-in-plugins/router-render.md
- docs/Reference/plugins/custom-plugins/create-a-plugin-function.md
- docs/Reference/plugins/custom-plugins/overview.md
- docs/Reference/plugins/custom-plugins/register-a-new-plugin.md
- docs/Reference/plugins/custom-plugins/use-a-custom-plugin.md
- docs/Reference/plugins/overview.md
- docs/Reference/plugins/types/allDone.md
- docs/Reference/plugins/types/fileHandler.md
- docs/Reference/plugins/types/overview.md
- docs/Reference/plugins/types/route-process.md
- docs/Reference/utilities/overview.md
- docs/concepts/overview.md
- docs/concepts/plugins.md
- docs/concepts/process.md
- docs/concepts/unhandled-routes.md
- docs/faq.md
- docs/learn/create-a-blog/add-blog-support.md
- docs/learn/create-a-blog/use-blog-post-data-in-template.md
- docs/learn/getting-started/building.md
- docs/learn/getting-started/installation.md
- docs/learn/introduction_es.md
- docs/learn/overview.md
- tests/jest/src/__tests__/docsThere.spec.ts
- tests/jest/src/test-config.helper.ts
broken internal links
Issue Number: 
Updated test to correctly test internal links, and fixed all the broken links
- [z] No
> docs(docsWeb): better test, and fix broken links

- libs/scully/src/scully.ts
> add node version check

- libs/scully/src/lib/renderPlugins/content-render-utils/readFileAndCheckPrePublishSlug.ts
> add future blog date in false if published true

- docs/Reference/command-line-options.md
- docs/Reference/config.md
- docs/Reference/ngLib/idle-monitor-service.md
- docs/Reference/ngLib/overview.md
- docs/Reference/ngLib/transfer-state-service.md
- docs/Reference/ngLib/utility-methods.md
- docs/Reference/plugins/built-in-plugins/md.md
- docs/Reference/plugins/built-in-plugins/router-render.md
- docs/Reference/schematics/create-blog-config.md
- docs/Reference/schematics/create-markdown-files-and-skeleton.md
- docs/Reference/schematics/create-scully-files-with-ng-add.md
- docs/Reference/schematics/overview.md
- docs/concepts/handled-routes.md
- docs/concepts/plugins.md
- docs/concepts/process.md
- docs/concepts/unhandled-routes.md
- docs/learn/create-a-blog/overview.md
- docs/learn/getting-started/overview.md
- docs/learn/getting-started/tips-for-testing.md
Updates documentation to improve readability.
There are a number of spelling and grammatical errors in the current version of documentation.
A number of documentation updates to improve readability.
> docs(docsWeb): improve documentation readability

- libs/plugins/scully-plugin-critical-css/README.md
- libs/scully/package.json
> Update critical readme

- .github/workflows/publish.yml
> update publish action

- libs/plugins/scully-plugin-critical-css/README.md
- libs/plugins/scully-plugin-critical-css/package.json
- libs/plugins/scully-plugin-critical-css/src/lib/plugins-scully-plugin-critical-css.ts
It only allows the file-name 'styles.css' for incoming styles.
Issue Number: 
It allows all names for incoming styles. It now reads the dis folder, and will use _all_ css files in there.
Also it allows for configuretion
> feat(lib): criticalPlugin(feat) add settings, and allow all css file-names

- docs/learn/getting-started/installation_es.md
> docs: ✏️ add learn/getting-started/installation_es.md

- docs/learn/getting-started/tips-for-testing.md
- docs/learn/getting-started/tips-for-testing_es.md
> docs: ✏️ add docs\learn\getting-started\tips-for-testing_es.md

- docs/learn/create-a-blog/overview_es.md
> docs: ✏️ add docs/learn/create-a-blog/overview_es.md

- docs/learn/create-a-blog/use-blog-post-data-in-template_es.md
> docs: ✏️ add create-a-blog/use-blog-post-data-in-template_es.md

- docs/learn/getting-started/building.md
- docs/learn/getting-started/building_es.md
> docs: ✏️ add docs/learn/getting-started/building_es.md

- docs/learn/getting-started/overview_es.md
> docs: ✏️ add learn\getting-started\overview_es.md

- docs/learn/getting-started/requirements_es.md
> docs: ✏️ add docs\learn\getting-started\requirements_es.md

- docs/learn/getting-started/serving_es.md
> docs: ✏️ add learn/getting-started/serving_es.md file

- docs/community/code-of-conduct_es.md
> docs: ✏️ add docs\community\code-of-conduct_es.md

- docs/community/contributing_es.md
> docs: ✏️ add docs\community\contributing_es.md

- docs/community/issues_es.md
> docs: ✏️ add docs\community\issues_es.md

- docs/community/overview_es.md
> docs: ✏️ add docs\community\overview_es.md

- docs/community/showcase_es.md
> docs: ✏️ add docs\community\showcase_es.md

- docs/community/sponsors_es.md
> docs: ✏️ add docs\community\sponsors_es.md

- docs/community/support_es.md
> docs: ✏️ add docs\community\support_es.md

- apps/scully-docs/src/app/app.component.css
- apps/scully-docs/src/app/app.component.ts
> feat(docsWeb): fix menu in mobile

- docs/concepts/process_es.md
> I18n/docs/concepts/process es.md

- docs/concepts/plugins_es.md
> I18n/docs/concepts/plugins es.md

- libs/plugins/scully-plugin-critical-css/README.md
- libs/plugins/scully-plugin-critical-css/package.json
- libs/plugins/scully-plugin-critical-css/src/lib/plugins-scully-plugin-critical-css.ts
There is a stale peerdep, and an user can't set asset folders
peerdep is removed, and a config setting for assets is added.
> fix(critical) remove unneeded peer dep, add Asset-folder to config

- docs/Reference/plugins/built-in-plugins/seoHrefOptimize_es.md
> I18n/docs/reference/plugins/built in plugins/seo href optimize es.md

- docs/Reference/plugins/built-in-plugins/router-_es.md
> I18n/docs/reference/plugins/built in plugins/router  es.md

- docs/Reference/plugins/built-in-plugins/router-render_es.md
> docs: ✏️ add built-in-plugins\router-render_es.md

- docs/Reference/plugins/built-in-plugins/overview_es.md
> I18n/docs/reference/plugins/built in plugins/overview es.md

- docs/Reference/plugins/built-in-plugins/md_es.md
> I18n/docs/reference/plugins/built in plugins/md es.md

- docs/Reference/plugins/built-in-plugins/json_es.md
> I18n/docs/reference/plugins/built in plugins/json es.md

- docs/Reference/plugins/built-in-plugins/ignored_es.md
> I18n/docs/reference/plugins/built in plugins/ignored es.md

- docs/Reference/ngLib/utility-methods.md
- docs/Reference/ngLib/utility-methods_es.md
> docs: ✏️ add docs\Reference\ngLib\utility-methods_es.md

- docs/Reference/ngLib/transfer-state-service_es.md
> docs: ✏️ add docs\Reference\ngLib\transfer-state-service_es.md

- docs/Reference/ngLib/scully-routes-service_es.md
> docs: ✏️ add docs\Reference\ngLib\scully-routes-service_es.md

- docs/Reference/ngLib/scully-content-component_es.md
> docs: ✏️ add docs\Reference\ngLib\scully-content-component_es.md

- docs/Reference/ngLib/overview_es.md
> docs: ✏️ add docs\Reference\ngLib\overview_es.md

- docs/Reference/ngLib/idle-monitor-service_es.md
> docs: ✏️ add docs\Reference\ngLib\idle-monitor-service_es.md

- docs/Reference/legacy-support/polyfills_es.md
> docs: ✏️ add docs\Reference\legacy-support\polyfills_es.md

- docs/Reference/legacy-support/overview_es.md
> docs: ✏️ add docs\Reference\legacy-support\overview_es.md

- docs/faq.md
- docs/faq_es.md
> I18n/docs/faq es.md

- apps/scully-docs/src/app/components/lang-select/component/lang-select/lang-select.component.css
- apps/scully-docs/src/app/components/lang-select/component/lang-select/lang-select.component.ts
> fix tab for change to spanish

- README.md
> fix misleading ml

- docs/Reference/plugins/community-plugins/lazyImages_es.md
> docs: ✏️ add community-plugins\lazyImages_es.md

- docs/Reference/plugins/community-plugins/disableAngular_es.md
> docs: ✏️ add community-plugins\disableAngular_es.md

- docs/Reference/plugins/community-plugins/fouc_es.md
> docs: ✏️ add community-plugins\fouc_es.md

- docs/Reference/plugins/community-plugins/http404_es.md
> docs: ✏️ add community-plugins\http404_es.md

- libs/scully-schematics/package.json
> remove ts dependency into schematics

- docs/concepts/handled-routes_es.md
- docs/concepts/unhandled-routes_es.md
> I18n/docs/concepts/unhandled routes es.md

- docs/Reference/plugins/community-plugins/mediumZoom_es.md
> docs: ✏️ add community-plugins\mediumZoom_es.md

- docs/Reference/plugins/community-plugins/minifyHtml_es.md
> docs: ✏️ add community-plugins\minifyHtml_es.md

- docs/Reference/plugins/community-plugins/overview_es.md
> docs: ✏️ add community-plugins\overview_es.md

- docs/Reference/plugins/community-plugins/regex_es.md
> docs: ✏️ add community-plugins\regex_es.md

- docs/Reference/plugins/community-plugins/rss_es.md
- docs/learn/create-a-blog/generate-new-blog-posts_es.md
> docs: ✏️ add community-plugins\rss_es.md

- docs/Reference/plugins/community-plugins/sitemap_es.md
> docs: ✏️ add community-plugins\sitemap_es.md

- docs/Reference/plugins/community-plugins/toc_es.md
> docs: ✏️ add community-plugins\toc_es.md

- docs/Reference/plugins/types/system.md
Typo in System Plugins Doc title
Fixed title typo
> docs: fix system plugins typo

- docs/Reference/plugins/types/fileHandler_es.md
> docs: ✏️ add types\fileHandler_es.md

- docs/Reference/plugins/custom-plugins/use-a-custom-plugin.md
- docs/Reference/plugins/custom-plugins/use-a-custom-plugin_es.md
> docs: ✏️ add custom-plugins\use-a-custom-plugin_es.md

- docs/Reference/plugins/custom-plugins/register-a-new-plugin_es.md
> docs: ✏️ add custom-plugins\register-a-new-plugin_es.md

- docs/Reference/plugins/custom-plugins/overview_es.md
> docs: ✏️ add custom-plugins\overview_es.md

- docs/Reference/plugins/custom-plugins/create-a-plugin-function_es.md
> docs: ✏️ add custom-plugins\create-a-plugin-function_es.md

- docs/Reference/plugins/types/allDone_es.md
> docs: ✏️ add types\allDone_es.md

- docs/Reference/plugins/types/route-process.md
- docs/Reference/plugins/types/route-process_es.md
> docs: ✏️ add types\route-process_es.md

- docs/Reference/plugins/types/routeDiscoveryDone_es.md
> docs: ✏️ add types\routeDiscoveryDone_es.md

- docs/Reference/plugins/types/router_es.md
> docs: ✏️ add types\router_es.md

- docs/Reference/plugins/overview.md
- docs/Reference/plugins/overview_es.md
- docs/Reference/plugins/types/overview_es.md
> docs: ✏️ add plugins\overview_es.md

- docs/Reference/schematics/create-blog-config.md
- docs/Reference/schematics/create-blog-config_es.md
> docs: ✏️ add schematics\create-blog-config_es.md

- docs/Reference/schematics/create-blog-config.md
- docs/Reference/schematics/create-blog-config_es.md
- docs/Reference/schematics/create-markdown-files-and-skeleton_es.md
> I18n/docs/reference/schematics/create markdown files and skeleton es.md

- docs/Reference/schematics/create-scully-files-with-ng-add_es.md
> docs: ✏️ add schematics\create-scully-files-with-ng-add_es.md

- docs/Reference/schematics/overview_es.md
> docs: ✏️ add schematics\overview_es.md

- docs/Reference/scully-api/overview-es.md
> docs: ✏️ add scully-api\overview-es.md

- docs/Reference/scully-api/registerPlugin_es.md
> docs: ✏️ add scully-api\registerPlugin_es.md

- docs/Reference/scully-api/utils_es.md
> docs: ✏️ add scully-api\utils_es.md

- docs/Reference/utilities/overview_es.md
> docs: ✏️ add utilities\overview_es.md

- docs/Reference/utilities/prism-js_es.md
> docs: ✏️ add utilities\prism-js_es.md

- docs/Reference/utilities/scully-publish_es.md
> docs: ✏️ add utilities\scully-publish_es.md

- docs/Reference/overview_es.md
> docs: ✏️ add docs\Reference\overview_es.md

- docs/Reference/plugins/types/system.md
- docs/Reference/plugins/types/system_es.md
> docs: ✏️ add types\system_es.md

- libs/scully/src/lib/utils/serverstuff/dataServer.ts
> feat(scully): add an way to optionally delay any request to our test server

- libs/plugins/base-href-rewrite/README.md
- libs/plugins/docs-link-update/README.md
- libs/plugins/extra/README.md
- libs/plugins/from-data/README.md
- libs/plugins/google-analytics/README.md
- libs/plugins/logrocket/README.md
- libs/plugins/scully-plugin-copy-to-clipboard/README.md
- libs/plugins/scully-plugin-critical-css/README.md
- libs/plugins/scully-plugin-flash-prevention/README.md
- libs/plugins/scully-plugin-remove-scripts/README.md
- libs/plugins/sentry/README.md
Issue Number: 1069: https://github.com/scullyio/scully/issues/1069
> docs: ✏️ base getting started for all plugins

- docs/Reference/ngLib/scully-content-component.md
[ScullyContentComponent](https://scully.io/docs/Reference/ngLib/scully-content-component/) document content doesn't look proper.
Updated the document
> docs: scully-content-component doc update

- docs/Reference/scully-api/overview_es.md
Fix typo in docs/Reference/scully-api/overview_es.md
> docs(docsWeb): DOCS rename docs\Reference\scully-api\overview_es.md

- docs/Reference/plugins/community-plugins/mediumZoom.md
> docs: update mediumZoom plugin title

- README.md
Readme full documentation link goes to a "Sorry, Could Not Load Static Page Content" page in the docs.
Readme full documentation link goes to the Introduction page explaining what Scully is.
> docs(docsWeb): readme full documentation link update to non broken link

- tests/jest/src/__tests__/readmesThere.spec.ts
add test to check overview.md files in every folder
ISSUES CLOSED: #887
Issue Number: #887 
This test passed green
> test(docsWeb): dOCS: add test to check overview.md files in every folder

- docs/concepts/overview_es.md
> docs(docsWeb): DOCS add docs\concepts\overview_es.md

- docs/Reference/plugins/types/route-process.md
> Update routeProccess documentation.

- docs/Reference/scully-api/utils.md
> docs: add httpGetJson util function documentation

- firebase.json
> add cache for images

- docs/learn/introduction.md
> add introduction md

- libs/scully/package.json
- libs/scully/src/lib/fileHanderPlugins/asciidoc.ts
- libs/scully/src/lib/utils/deepClone.ts
- tests/jest/src/__tests__/__snapshots__/blog-index.spec.ts.snap
- tests/jest/src/__tests__/blog-index.spec.ts
> fix(scully): fix dates getting lost in deepclone (for routeProcessed)

- apps/scully-docs/src/app/pages/landing/components/features/features.component.ts
The current link does not redirect to the correct page
Issue Number: #1139 
The link will redirect to the correct page
> Fix broken link

- docs/Reference/plugins/community-plugins/meetup.md
This will add a new plugin to the community plugin part of scully
> docs: add meetup community plugin

- docs/Reference/plugins/built-in-plugins/json.md
Provide examples of each of the options for the json plugin, though the main purpose was to add documentation around the `resultsHandler`.
Docs were missing any mentioned of the `resultsHandler`. Fixed now. 
> docs(scully): Add `resultsHandler` documentation

- docs/community/showcase.md
Added a new showcase entry for Meme Composer site
> docs: Update showcase.md file

- docs/Reference/plugins/built-in-plugins/criticalcss.md
- docs/Reference/plugins/built-in-plugins/flashPrevention.md
- libs/plugins/scully-plugin-critical-css/README.md
Documentation
Issue Number: #1135 
Docs added for both critical css and flash-prevention
Closes #1135
> fix(doc): critical css and flash-prevention document added

- docs/Reference/plugins/community-plugins/canonical.md
docs: add scully-plugin-canonical
Added the scully-plugin-canonical information to the community plugin list
Adds a new community plugin to the list
> Add scully-plugin-canonical

- docs/Reference/plugins/community-plugins/amp-css.md
docs: added scully-plugin-amp-css to community plugins list
Added the new scully-plugin-amp-css to the community plugins docs page
Relates to issue #1132
Added the scully-plugin-amp-css to the community plugins page
Issue Number: #1132
> AMP CSS Plugin Community Page

- libs/scully/src/lib/startBackgroundServer.ts
- [ x] The commit message follows our guidelines: https://github.com/scullyio/scully/blob/main/CONTRIBUTING.md#commit
- [x ] Tests for the changes have been added (for bug fixes / features)
- [x ] Docs have been added / updated (for bug fixes / features)
- [x ] Bugfix
Use path.join() to add paths.  Fixes a path issue when building scully.
- [x ] No
> fix: baseBinary not compatible with windows builds, also pointing to wrong folder

- libs/scully/package.json
- libs/scully/src/lib/renderPlugins/puppeteerRenderPlugin.ts
Version number isn't correctly determined
> fix scully version number in generated HTML

- docs/Reference/plugins/community-plugins/rss.md
* updated to new plugin type `routeDiscoveryDone`
> docs(rss): update to reflect new release

- docs/Reference/scully-api/findPlugin.md
- docs/Reference/scully-api/overview.md
docs: document the findPlugin function
document the findPlugin and how to use it
ISSUES CLOSED: #1180
There was no documentation for `findPlugin`
Issue Number: #1180
This provides documentation for `findPlugin`.
> Document the findPlugin Method

- docs/Reference/plugins/community-plugins/canonical.md
docs: fixed the plugin page title
> Fix Plugin Docs Page Title

- libs/ng-lib/package.json
- libs/ng-lib/src/lib/transfer-state/transfer-state.service.ts
- libs/scully/package.json
- libs/scully/src/lib/pluginManagement/Plugin.interfaces.ts
- libs/scully/src/lib/pluginManagement/pluginRepository.ts
- libs/scully/src/lib/systemPlugins/writeToFs.plugin.ts
- libs/scully/src/lib/testData/users-testdata.ts
- libs/scully/src/lib/utils/scullydot.ts
- scully.scully-docs.config.ts
- tests/jest/src/__tests__/__snapshots__/users.spec.ts.snap
- tests/jest/src/test-config.helper.ts
> fix(monorepo): fix transferstate so it allows backticks

- libs/scully/src/lib/utils/log.ts
Issue Number: #1205
Arguments other than strings and Errors are logged
> fix(scully): log other arguments than strings and errors

- .github/workflows/new-project.yaml
- .github/workflows/nodejs.yml
- .github/workflows/publish.yml
> change GA to node14

- .github/workflows/changelog.yml
> CI(monorepo): add automatic changelog

- docs/learn/getting-started/requirements.md
- [x ] Other... Please describe: documenation
- [ x] No
> adding missing link for installation

- libs/plugins/scully-plugin-local-cache/src/lib/generateId.ts
- libs/plugins/scully-plugin-local-cache/src/lib/handlePuppeteerRequest.ts
- libs/plugins/scully-plugin-local-cache/src/lib/handlePuppeteerResponse.ts
- package-lock.json
- scully.scully-docs.config.ts
> fix(lib): local_cache include ID and environment into cache key's

- .github/workflonpmpublish.yml
> Create workflow for publishing to NPM

- docs/Reference/ngLib/idle-monitor-service.md
- docs/community/starters.md
> feat(docsWeb): (docs) Add community starters page

- .github/workflows/testartifact.yml
- docs/Reference/ngLib/idle-monitor-service.md
- docs/Reference/plugins/community-plugins/page-title_es.md
- docs/Reference/plugins/community-plugins/time-to-read_es.md
- docs/Reference/scully-api/findPlugin_es.md
- docs/community/starters.md
- libs/scully/package-lock.json
- libs/scully/package.json
- package-lock.json
- package.json
> Sander elias patch 1

- libs/scully-schematics/src/ng-add/index.ts
- libs/scully-schematics/src/utils/utils.ts
- releaseChecksums.json
…ructure, add more error message and how can fix
- [] Docs have been added / updated (for bug fixes / features)
Issue Number: #1263 #1264 #1265 
closes #1263 #1264 #1265
> Fix(schematics): fix issue when the angular.json file have the old structure, add more error message and how can fix

- docs/community/starters.md
> Scully starters section update

- libs/scully/src/lib/renderPlugins/launchedBrowser.ts
- releaseChecksums.json
> fix(scully): add proper error when puppeteer fails to launch

- docs/learn/create-a-plugin/create-a-plugin.md
docs(scully): add a guide on how to create a custom scully plugin
Add a guide to show users how to create custom plugins for their scully apps
Teaches them about
the types of plugins, useful functions
New guide for creating custom scully plugins
> Custom Scully Plugin Guide

- libs/plugins/scully-plugin-local-cache/src/index.ts
- libs/plugins/scully-plugin-local-cache/src/lib/handlePuppeteerResponse.ts
- libs/plugins/scully-plugin-local-cache/src/lib/local-cache.interface.ts
- package-lock.json
- package.json
- tools/autoVersion.ts
- tools/publishPackage.ts
- tools/releaseChecksums.develop.json
props not in cache
props are in the cache, so we can use them to filter in the vault
> fix(scully-plugin-local-cache): add enviroment and project to cacheItem

- libs/scully/src/lib/pluginManagement/pluginConfig.ts
> fix(scully): makes sure calls to getConfig(plugin, 'render') won't break

- libs/scully-schematics/src/scully/index.ts
Reverts scullyio/scully#1273 merged by accident
> Revert "fix(schematics): fix the scripts in package.json"

- libs/scully-schematics/package.json
- libs/scully-schematics/src/scully/index.ts
> fix: 🐛 Fix Schematic so npm run scully works

- docs/learn/use-netlify-cms/use-netlify-cms.md
docs: add Netlify CMS guide
Add a guide to show users how to use Netlify CMS with their Scully app/site
Brief guide on setting up Netlify CMS with your Scully site.
> Scully + Netlify CMS Guide

- docs/Reference/plugins/overview.md
It fixes a link in the docs.
The postProcessByDom and postProcessByHtml plugin links both point to the description of postProcessByHtml plugins.
> docs(plugins): fix postProcessByDom plugins link

- docs/learn/use-netlify-cms/use-netlify-cms.md
- workspace.json
> fix(schematics): publish json files to dist folder

- .gitignore
- libs/ng-lib/package.json
- libs/plugins/base-href-rewrite/package.json
- libs/plugins/docs-link-update/package.json
- libs/plugins/extra/package.json
- libs/plugins/from-data/package.json
- libs/plugins/google-analytics/package.json
- libs/plugins/logrocket/package.json
- libs/plugins/scully-plugin-copy-to-clipboard/package.json
- libs/plugins/scully-plugin-critical-css/package.json
- libs/plugins/scully-plugin-flash-prevention/package.json
- libs/plugins/scully-plugin-local-cache/package.json
- libs/plugins/scully-plugin-remove-scripts/package.json
- libs/plugins/sentry/package.json
- libs/scully-schematics/package.json
- libs/scully/package.json
- tools/releaseChecksums.release.json
- tools/utils.ts
Upated package versions and released a patch version to NPM
> chore(monorepo): released a new patch version of updated packages(all)

- docs/Reference/plugins/types/route-process.md
> docs: remove wrong part about config of routeProcess plugins

- docs/Reference/ngLib/idle-monitor-service.md
- [x ] The commit message follows our guidelines: https://github.com/scullyio/scully/blob/main/CONTRIBUTING.md#commit
- [x ] Refactoring (no functional changes, no api changes)
- [ x] No
> docs: update manualIdle to manualIdleCheck

- docs/concepts/handled-routes.md
- [x ] The commit message follows our guidelines: https://github.com/scullyio/scully/blob/main/CONTRIBUTING.md#commit
- [x ] Refactoring (no functional changes, no api changes)
- [ x] No
> docs: swap contentTestPlugin to contentTextPlugin

- .github/workflows/workflow.yml
- [X ] The commit message follows our guidelines: https://github.com/scullyio/scully/blob/main/CONTRIBUTING.md#commit
This PR will test multiple node and angular versions as a last step.
Issue Number: #1271
> ci: add e2e platform tests

- docs/faq.md
> docs: change buiild to build

- docs/Reference/legacy-support/angular-v8_es.md
The spanish version of the section 'Releasing an Angular v8.x.x Library' is included into the english version of the docs 
By updating the metadata of the markdown file, the spanish version will be included into the spanish version of the docs.
> docs(reference): fix language

- docs/community/starters.md
The table of contents of the Starter page of the docs is full of 'Details' sections.
Issue Number: #1317 
The table of contents contains the name of each section.
> fix(docs): fix table of contents section titles

- .github/workflows/pull_approver.yml
- .github/workflows/workflow.yml
> ci: only publish on merge

- libs/scully/src/lib/utils/startup.ts
> fix(scully): (fix) Scully: force exit on ready, to prevent CI/CD stall

- libs/scully/src/index.ts
- libs/scully/src/lib/pluginManagement/pluginConfig.ts
It is currently not possible to overwrite the priority of a route process plugin.
Issue Number: #1305
This PR adds a function to set the priority of a route process plugin.
> feat: add function to configure plugin priority

- .github/workflows/workflow.yml
- workspace.json
- [ X] The commit message follows our guidelines: https://github.com/scullyio/scully/blob/main/CONTRIBUTING.md#commit
With this change we are publishing the schematics template files
- [ X] Bugfix
> fix(schematics): package should contain template files

- apps/scully-docs/src/app/app-routing.module.ts
- apps/scully-docs/src/app/app.component.ts
- apps/scully-docs/src/app/pages/extraPages/extra-page.module.ts
- scully.scully-docs.config.ts
> feat(docsWeb): add ngconf 2021 page

- libs/scully-schematics/package.json
- tools/deployReleasets.ts
- tools/releaseChecksums.develop.json
- tools/releaseChecksums.release.json
> chore(schematics): publish last version

- .github/workflows/workflow.yml
> ci: add cache key to invalidte GH actions cache

- .github/workflows/workflow.yml
test fails on node 14
we are now only testing with node versions supported by the CLI. this has somehow become more restrictive.
> chore(monorepo): remove NG unsupported versions from test suite

- libs/scully-schematics/src/add-blog/schema.json
- libs/scully-schematics/src/add-plugin/schema.json
- libs/scully-schematics/src/add-post/schema.json
- libs/scully-schematics/src/collection.json
- libs/scully-schematics/src/create-markdown/schema.json
- libs/scully-schematics/src/ng-add/schema.json
- libs/scully-schematics/src/plugin-ts/schema.json
- libs/scully-schematics/src/route-discovery/schema.json
- libs/scully-schematics/src/scully/schema.json
> fix: use new id property in schematics

- libs/plugins/scully-plugin-flash-prevention/README.md
> docs(scully-plugin-flash-prevention): reapply a lost docs update

- docs/faq.md
> docs(docsWeb): mention puppeteer launch options in docker config in FAQ

- .vscode/extensions.json
> chore: remove recommandation for tslint extentions for vscode

- libs/scully/src/lib/utils/exitHandler.ts
Sometimes Scully hangs during exit, especially in CI/CD
SHould not hang anymore
> fix(scully): make sure exit takes place, even when errors happen, or puppeteer stalled

- libs/plugins/scully-plugin-critical-css/package.json
- package-lock.json
> Update critical package to 4.0.1 in @scullyio/scully-plugin-critical-css

- docs/consutancy.md
> docs: remove dot in heading

- docs/consutancy.md
I've should also remove the DOT from the title.
> docs: remove dot in title

- docs/Reference/config.md
- docs/Reference/config_es.md
- libs/scully/src/lib/renderPlugins/launchedBrowser.ts
- libs/scully/src/lib/utils/interfacesandenums.ts
`puppeteerLaunchOptions` is typed as `LaunchOptions`
Issue Number: #1451
`puppeteerLaunchOptions` is typed as `PuppeteerNodeLaunchOptions`
> fix(scully): fix type of puppeteerLaunchOptions (#1451)

- docs/learn/getting-started/building.md
> Remove deprecated prod option

- libs/plugins/scully-plugin-flash-prevention/tsconfig.lib.json
> fix(scully-plugin-flash-prevention): make the build generate type definitions

- .github/CODEOWNERS
> chore: add codeowners for auto assign

- apps/sample-blog/src/app/app.sps.module.ts
- apps/scully-docs/src/app/app.sps.module.ts
- apps/sps-sample/src/app/app.sps.module.ts
- libs/scully/src/lib/fileHanderPlugins/asciidoc.ts
- libs/scully/src/lib/utils/serverstuff/handleUnknownRoute.ts
> fix(monorepo): remove some comments, and update module names according to comments in #1459

- libs/ng-lib/package.json
- libs/platform-server/package.json
- libs/plugins/base-href-rewrite/package.json
- libs/plugins/docs-link-update/package.json
- libs/plugins/extra/package.json
- libs/plugins/from-data/package.json
- libs/plugins/google-analytics/package.json
- libs/plugins/logrocket/package.json
- libs/plugins/scully-plugin-copy-to-clipboard/package.json
- libs/plugins/scully-plugin-critical-css/package.json
- libs/plugins/scully-plugin-flash-prevention/package.json
- libs/plugins/scully-plugin-local-cache/package.json
- libs/plugins/scully-plugin-remove-scripts/package.json
- libs/plugins/sentry/package.json
- libs/scully-schematics/package.json
- libs/scully-schematics/src/utils/utils.ts
- libs/scully/package.json
- tools/releaseChecksums.release.json
> chore(monorepo): update schematic to work with V13 and update package numbers to reflect latest npm release

- package-lock.json
- package.json
- scully.scully-docs.config.ts
> fix(docsWeb): switch to critters for CSS inlining, because critical is causing a 98% cpu load issue.

- .husky/commit-msg
- .husky/pre-commit
- commitlint.config.js
- package-lock.json
- package.json
> chore: support linting on commit

- libs/scully-schematics/src/ng-add/index.ts
- libs/scully-schematics/src/ng-add/schema.json
- libs/scully-schematics/src/ng-add/schema.ts
- libs/scully-schematics/src/scully/index.ts
add question to install route renderer and update config
With this PR we ask users the question of which render can should be added and installed.
> feat(schematics): add question wich route renderer should be installed

- .github/workflows/release.yml
> chore(Actions): add action to create new release after push a new tag

- libs/plugins/google-analytics/README.md
Documentation was out of date.
N/A
N/A
This pull request correct the Google Analytics documentation example. The import was incorrect.
> Fix Google Analytics documentation example

- .github/workflows/bumpAndTag.yml
> add the bots pat to the checkout

- libs/scully/src/lib/utils/startup/scullyInit.ts
> fix: typo inside scullyInit.ts

- libs/ng-lib/package.json
- libs/platform-server/package.json
> feat(platform-server): limit to version 12, as version 13 needs ESM

- libs/ng-lib/src/lib/transfer-state/transfer-state.service.ts
- package-lock.json
- package.json
> fix(ng-lib): don't error when routing from non-Scully page to Scully-genreated page

- libs/scully-schematics/src/ng-add/index.ts
> fix(schematics): make sure the schematics install the latest version off our playwright plugin, instead of 0.0.2

- docs/faq.md
> docs(docsWeb): add FAQ about `--` and `--scanRoutes`

- libs/ng-lib/src/lib/transfer-state/transfer-state.service.ts
- libs/scully/src/lib/testData/users-testdata.ts
- libs/scully/src/lib/utils/startup/startup.ts
- package-lock.json
> fix(ng-lib): allow for a backslash in Transerstate contents

- docs/learn/overview.md
Documentation
As is.
Doc update
N/A
> Non-major documentation updates
